import type { Country } from "@/types";

export const seedCountries: Country[] = [
  // === Existing (priority — source markets) ===
  {
    code: "AZ",
    slug: "azerbaijan",
    flag: "🇦🇿",
    name: {
      en: "Azerbaijan",
      tr: "Azerbaycan",
      az: "Azərbaycan",
      ru: "Азербайджан",
      de: "Aserbaidschan",
      fr: "Azerbaïdjan",
      fa: "آذربایجان",
      ar: "أذربيجان",
      tk: "Azerbaýjan",
      kk: "Әзірбайжан",
      ky: "Азербайжан",
      zh: "阿塞拜疆",
      bg: "Азербайджан",
      ur: "آذربائیجان",
      uz: "Ozarbayjon",
      sw: "Azerbaijani",
      so: "Asarbayjan",
      id: "Azerbaijan",
    },
  },
  {
    code: "UZ",
    slug: "uzbekistan",
    flag: "🇺🇿",
    name: {
      en: "Uzbekistan",
      tr: "Özbekistan",
      az: "Özbəkistan",
      ru: "Узбекистан",
      de: "Usbekistan",
      fr: "Ouzbékistan",
      fa: "ازبکستان",
      ar: "أوزبكستان",
      tk: "Özbegistan",
      kk: "Өзбекстан",
      ky: "Өзбекстан",
      zh: "乌兹别克斯坦",
      bg: "Узбекистан",
      ur: "ازبکستان",
      uz: "Oʻzbekiston",
      sw: "Uzbekistan",
      so: "Usbekistan",
      id: "Uzbekistan",
    },
  },
  {
    code: "RU",
    slug: "russia",
    flag: "🇷🇺",
    name: {
      en: "Russia",
      tr: "Rusya",
      az: "Rusiya",
      ru: "Россия",
      de: "Russland",
      fr: "Russie",
      fa: "روسیه",
      ar: "روسيا",
      tk: "Russiýa",
      kk: "Ресей",
      ky: "Орусия",
      zh: "俄罗斯",
      bg: "Русия",
      ur: "روس",
      uz: "Rossiya",
      sw: "Urusi",
      so: "Ruushka",
      id: "Rusia",
    },
  },
  {
    code: "KZ",
    slug: "kazakhstan",
    flag: "🇰🇿",
    name: {
      en: "Kazakhstan",
      tr: "Kazakistan",
      az: "Qazaxıstan",
      ru: "Казахстан",
      de: "Kasachstan",
      fr: "Kazakhstan",
      fa: "قزاقستان",
      ar: "كازاخستان",
      tk: "Gazagystan",
      kk: "Қазақстан",
      ky: "Казакстан",
      zh: "哈萨克斯坦",
      bg: "Казахстан",
      ur: "قازقستان",
      uz: "Qozogʻiston",
      sw: "Kazakhstan",
      so: "Kasaqstan",
      id: "Kazakhstan",
    },
  },
  {
    code: "TM",
    slug: "turkmenistan",
    flag: "🇹🇲",
    name: {
      en: "Turkmenistan",
      tr: "Türkmenistan",
      az: "Türkmənistan",
      ru: "Туркменистан",
      de: "Turkmenistan",
      fr: "Turkménistan",
      fa: "ترکمنستان",
      ar: "تركمانستان",
      tk: "Türkmenistan",
      kk: "Түрікменстан",
      ky: "Түркмөнстан",
      zh: "土库曼斯坦",
      bg: "Туркменистан",
      ur: "ترکمانستان",
      uz: "Turkmaniston",
      sw: "Turkmenistan",
      so: "Turkmenistan",
      id: "Turkmenistan",
    },
  },
  {
    code: "KG",
    slug: "kyrgyzstan",
    flag: "🇰🇬",
    name: {
      en: "Kyrgyzstan",
      tr: "Kırgızistan",
      az: "Qırğızıstan",
      ru: "Кыргызстан",
      de: "Kirgisistan",
      fr: "Kirghizistan",
      fa: "قرقیزستان",
      ar: "قيرغيزستان",
      tk: "Gyrgyzystan",
      kk: "Қырғызстан",
      ky: "Кыргызстан",
      zh: "吉尔吉斯斯坦",
      bg: "Киргизия",
      ur: "کرغزستان",
      uz: "Qirgʻiziston",
      sw: "Kirigizistan",
      so: "Qirgizistan",
      id: "Kirgizstan",
    },
  },
  {
    code: "PK",
    slug: "pakistan",
    flag: "🇵🇰",
    name: {
      en: "Pakistan",
      tr: "Pakistan",
      az: "Pakistan",
      ru: "Пакистан",
      de: "Pakistan",
      fr: "Pakistan",
      fa: "پاکستان",
      ar: "باكستان",
      tk: "Pakistan",
      kk: "Пәкістан",
      ky: "Пакистан",
      zh: "巴基斯坦",
      bg: "Пакистан",
      ur: "پاکستان",
      uz: "Pokiston",
      sw: "Pakistan",
      so: "Bakistaan",
      id: "Pakistan",
    },
  },
  {
    code: "NG",
    slug: "nigeria",
    flag: "🇳🇬",
    name: {
      en: "Nigeria",
      tr: "Nijerya",
      az: "Nigeriya",
      ru: "Нигерия",
      de: "Nigeria",
      fr: "Nigeria",
      fa: "نیجریه",
      ar: "نيجيريا",
      tk: "Nigeriýa",
      kk: "Нигерия",
      ky: "Нигерия",
      zh: "尼日利亚",
      bg: "Нигерия",
      ur: "نائیجیریا",
      uz: "Nigeriya",
      sw: "Nigeria",
      so: "Nayjeeriya",
      id: "Nigeria",
    },
  },
  {
    code: "IR",
    slug: "iran",
    flag: "🇮🇷",
    name: {
      en: "Iran",
      tr: "İran",
      az: "İran",
      ru: "Иран",
      de: "Iran",
      fr: "Iran",
      fa: "ایران",
      ar: "إيران",
      tk: "Eýran",
      kk: "Иран",
      ky: "Иран",
      zh: "伊朗",
      bg: "Иран",
      ur: "ایران",
      uz: "Eron",
      sw: "Iran",
      so: "Iiraan",
      id: "Iran",
    },
  },
  {
    code: "IQ",
    slug: "iraq",
    flag: "🇮🇶",
    name: {
      en: "Iraq",
      tr: "Irak",
      az: "İraq",
      ru: "Ирак",
      de: "Irak",
      fr: "Irak",
      fa: "عراق",
      ar: "العراق",
      tk: "Yrak",
      kk: "Ирак",
      ky: "Ирак",
      zh: "伊拉克",
      bg: "Ирак",
      ur: "عراق",
      uz: "Iroq",
      sw: "Iraki",
      so: "Ciraaq",
      id: "Irak",
    },
  },
  {
    code: "TR",
    slug: "turkey",
    flag: "🇹🇷",
    name: {
      en: "Turkey",
      tr: "Türkiye",
      az: "Türkiyə",
      ru: "Турция",
      de: "Türkei",
      fr: "Turquie",
      fa: "ترکیه",
      ar: "تركيا",
      tk: "Türkiýe",
      kk: "Түркия",
      ky: "Түркия",
      zh: "土耳其",
      bg: "Турция",
      ur: "ترکی",
      uz: "Turkiya",
      sw: "Uturuki",
      so: "Turkiga",
      id: "Turki",
    },
  },

  // === Europe ===
  {
    code: "DE",
    slug: "germany",
    flag: "🇩🇪",
    name: {
      en: "Germany",
      tr: "Almanya",
      az: "Almaniya",
      ru: "Германия",
      de: "Deutschland",
      fr: "Allemagne",
      fa: "آلمان",
      ar: "ألمانيا",
      tk: "Germaniýa",
      kk: "Германия",
      ky: "Германия",
      zh: "德国",
      bg: "Германия",
      ur: "جرمنی",
      uz: "Germaniya",
      sw: "Ujerumani",
      so: "Jarmalka",
      id: "Jerman",
    },
  },
  {
    code: "FR",
    slug: "france",
    flag: "🇫🇷",
    name: {
      en: "France",
      tr: "Fransa",
      az: "Fransa",
      ru: "Франция",
      de: "Frankreich",
      fr: "France",
      fa: "فرانسه",
      ar: "فرنسا",
      tk: "Fransiýa",
      kk: "Франция",
      ky: "Франция",
      zh: "法国",
      bg: "Франция",
      ur: "فرانس",
      uz: "Fransiya",
      sw: "Ufaransa",
      so: "Faransiiska",
      id: "Prancis",
    },
  },
  {
    code: "GB",
    slug: "united-kingdom",
    flag: "🇬🇧",
    name: {
      en: "United Kingdom",
      tr: "İngiltere",
      az: "Böyük Britaniya",
      ru: "Великобритания",
      de: "Vereinigtes Königreich",
      fr: "Royaume-Uni",
      fa: "بریتانیا",
      ar: "المملكة المتحدة",
      tk: "Beýik Britaniýa",
      kk: "Ұлыбритания",
      ky: "Улуу Британия",
      zh: "英国",
      bg: "Обединено кралство",
      ur: "برطانیہ",
      uz: "Buyuk Britaniya",
      sw: "Uingereza",
      so: "Boqortooyada Ingiriiska",
      id: "Inggris Raya",
    },
  },
  {
    code: "IT",
    slug: "italy",
    flag: "🇮🇹",
    name: {
      en: "Italy",
      tr: "İtalya",
      az: "İtaliya",
      ru: "Италия",
      de: "Italien",
      fr: "Italie",
      fa: "ایتالیا",
      ar: "إيطاليا",
      tk: "Italiýa",
      kk: "Италия",
      ky: "Италия",
      zh: "意大利",
      bg: "Италия",
      ur: "اٹلی",
      uz: "Italiya",
      sw: "Italia",
      so: "Talyaaniga",
      id: "Italia",
    },
  },
  {
    code: "ES",
    slug: "spain",
    flag: "🇪🇸",
    name: {
      en: "Spain",
      tr: "İspanya",
      az: "İspaniya",
      ru: "Испания",
      de: "Spanien",
      fr: "Espagne",
      fa: "اسپانیا",
      ar: "إسبانيا",
      tk: "Ispaniýa",
      kk: "Испания",
      ky: "Испания",
      zh: "西班牙",
      bg: "Испания",
      ur: "ہسپانیہ",
      uz: "Ispaniya",
      sw: "Uhispania",
      so: "Isbaanish",
      id: "Spanyol",
    },
  },
  {
    code: "NL",
    slug: "netherlands",
    flag: "🇳🇱",
    name: {
      en: "Netherlands",
      tr: "Hollanda",
      az: "Niderland",
      ru: "Нидерланды",
      de: "Niederlande",
      fr: "Pays-Bas",
      fa: "هلند",
      ar: "هولندا",
      tk: "Gollandiýa",
      kk: "Нидерланд",
      ky: "Нидерланд",
      zh: "荷兰",
      bg: "Нидерландия",
      ur: "نیدرلینڈ",
      uz: "Niderlandiya",
      sw: "Uholanzi",
      so: "Nederlaan",
      id: "Belanda",
    },
  },
  {
    code: "BE",
    slug: "belgium",
    flag: "🇧🇪",
    name: {
      en: "Belgium",
      tr: "Belçika",
      az: "Belçika",
      ru: "Бельгия",
      de: "Belgien",
      fr: "Belgique",
      fa: "بلژیک",
      ar: "بلجيكا",
      tk: "Belgiýa",
      kk: "Бельгия",
      ky: "Бельгия",
      zh: "比利时",
      bg: "Белгия",
      ur: "بیلجیم",
      uz: "Belgiya",
      sw: "Ubelgiji",
      so: "Beljiyam",
      id: "Belgia",
    },
  },
  {
    code: "AT",
    slug: "austria",
    flag: "🇦🇹",
    name: {
      en: "Austria",
      tr: "Avusturya",
      az: "Avstriya",
      ru: "Австрия",
      de: "Österreich",
      fr: "Autriche",
      fa: "اتریش",
      ar: "النمسا",
      tk: "Awstriýa",
      kk: "Аустрия",
      ky: "Австрия",
      zh: "奥地利",
      bg: "Австрия",
      ur: "آسٹریا",
      uz: "Avstriya",
      sw: "Austria",
      so: "Awsteriya",
      id: "Austria",
    },
  },
  {
    code: "CH",
    slug: "switzerland",
    flag: "🇨🇭",
    name: {
      en: "Switzerland",
      tr: "İsviçre",
      az: "İsveçrə",
      ru: "Швейцария",
      de: "Schweiz",
      fr: "Suisse",
      fa: "سوئیس",
      ar: "سويسرا",
      tk: "Şweýsariýa",
      kk: "Швейцария",
      ky: "Швейцария",
      zh: "瑞士",
      bg: "Швейцария",
      ur: "سوئٹزرلینڈ",
      uz: "Shveytsariya",
      sw: "Uswisi",
      so: "Swiiserlaand",
      id: "Swiss",
    },
  },
  {
    code: "SE",
    slug: "sweden",
    flag: "🇸🇪",
    name: {
      en: "Sweden",
      tr: "İsveç",
      az: "İsveç",
      ru: "Швеция",
      de: "Schweden",
      fr: "Suède",
      fa: "سوئد",
      ar: "السويد",
      tk: "Şwesiýa",
      kk: "Швеция",
      ky: "Швеция",
      zh: "瑞典",
      bg: "Швеция",
      ur: "سویڈن",
      uz: "Shvetsiya",
      sw: "Uswidi",
      so: "Iswidhan",
      id: "Swedia",
    },
  },
  {
    code: "NO",
    slug: "norway",
    flag: "🇳🇴",
    name: {
      en: "Norway",
      tr: "Norveç",
      az: "Norveç",
      ru: "Норвегия",
      de: "Norwegen",
      fr: "Norvège",
      fa: "نروژ",
      ar: "النرويج",
      tk: "Norwegiýa",
      kk: "Норвегия",
      ky: "Норвегия",
      zh: "挪威",
      bg: "Норвегия",
      ur: "ناروے",
      uz: "Norvegiya",
      sw: "Norway",
      so: "Noorweey",
      id: "Norwegia",
    },
  },
  {
    code: "DK",
    slug: "denmark",
    flag: "🇩🇰",
    name: {
      en: "Denmark",
      tr: "Danimarka",
      az: "Danimarka",
      ru: "Дания",
      de: "Dänemark",
      fr: "Danemark",
      fa: "دانمارک",
      ar: "الدنمارك",
      tk: "Daniýa",
      kk: "Дания",
      ky: "Дания",
      zh: "丹麦",
      bg: "Дания",
      ur: "ڈنمارک",
      uz: "Daniya",
      sw: "Denmark",
      so: "Danmark",
      id: "Denmark",
    },
  },
  {
    code: "FI",
    slug: "finland",
    flag: "🇫🇮",
    name: {
      en: "Finland",
      tr: "Finlandiya",
      az: "Finlandiya",
      ru: "Финляндия",
      de: "Finnland",
      fr: "Finlande",
      fa: "فنلاند",
      ar: "فنلندا",
      tk: "Finlýandiýa",
      kk: "Финляндия",
      ky: "Финляндия",
      zh: "芬兰",
      bg: "Финландия",
      ur: "فن لینڈ",
      uz: "Finlandiya",
      sw: "Ufini",
      so: "Finland",
      id: "Finlandia",
    },
  },
  {
    code: "PL",
    slug: "poland",
    flag: "🇵🇱",
    name: {
      en: "Poland",
      tr: "Polonya",
      az: "Polşa",
      ru: "Польша",
      de: "Polen",
      fr: "Pologne",
      fa: "لهستان",
      ar: "بولندا",
      tk: "Polşa",
      kk: "Польша",
      ky: "Польша",
      zh: "波兰",
      bg: "Полша",
      ur: "پولینڈ",
      uz: "Polsha",
      sw: "Poland",
      so: "Booland",
      id: "Polandia",
    },
  },
  {
    code: "UA",
    slug: "ukraine",
    flag: "🇺🇦",
    name: {
      en: "Ukraine",
      tr: "Ukrayna",
      az: "Ukrayna",
      ru: "Украина",
      de: "Ukraine",
      fr: "Ukraine",
      fa: "اوکراین",
      ar: "أوكرانيا",
      tk: "Ukraina",
      kk: "Украина",
      ky: "Украина",
      zh: "乌克兰",
      bg: "Украйна",
      ur: "یوکرین",
      uz: "Ukraina",
      sw: "Ukraine",
      so: "Yukrayn",
      id: "Ukraina",
    },
  },
  {
    code: "BY",
    slug: "belarus",
    flag: "🇧🇾",
    name: {
      en: "Belarus",
      tr: "Belarus",
      az: "Belarus",
      ru: "Беларусь",
      de: "Belarus",
      fr: "Biélorussie",
      fa: "بلاروس",
      ar: "بيلاروسيا",
      tk: "Belarus",
      kk: "Беларусь",
      ky: "Беларусь",
      zh: "白俄罗斯",
      bg: "Беларус",
      ur: "بیلاروس",
      uz: "Belarus",
      sw: "Belarus",
      so: "Belarus",
      id: "Belarus",
    },
  },
  {
    code: "RO",
    slug: "romania",
    flag: "🇷🇴",
    name: {
      en: "Romania",
      tr: "Romanya",
      az: "Rumıniya",
      ru: "Румыния",
      de: "Rumänien",
      fr: "Roumanie",
      fa: "رومانی",
      ar: "رومانيا",
      tk: "Rumyniýa",
      kk: "Румыния",
      ky: "Румыния",
      zh: "罗马尼亚",
      bg: "Румъния",
      ur: "رومانیہ",
      uz: "Ruminiya",
      sw: "Rumania",
      so: "Rumaaniya",
      id: "Rumania",
    },
  },
  {
    code: "BG",
    slug: "bulgaria",
    flag: "🇧🇬",
    name: {
      en: "Bulgaria",
      tr: "Bulgaristan",
      az: "Bolqarıstan",
      ru: "Болгария",
      de: "Bulgarien",
      fr: "Bulgarie",
      fa: "بلغارستان",
      ar: "بلغاريا",
      tk: "Bolgariýa",
      kk: "Болгария",
      ky: "Болгария",
      zh: "保加利亚",
      bg: "България",
      ur: "بلغاریہ",
      uz: "Bolgariya",
      sw: "Bulgaria",
      so: "Bulgaariya",
      id: "Bulgaria",
    },
  },
  {
    code: "GR",
    slug: "greece",
    flag: "🇬🇷",
    name: {
      en: "Greece",
      tr: "Yunanistan",
      az: "Yunanıstan",
      ru: "Греция",
      de: "Griechenland",
      fr: "Grèce",
      fa: "یونان",
      ar: "اليونان",
      tk: "Gresiýa",
      kk: "Греция",
      ky: "Греция",
      zh: "希腊",
      bg: "Гърция",
      ur: "یونان",
      uz: "Gretsiya",
      sw: "Ugiriki",
      so: "Giriig",
      id: "Yunani",
    },
  },
  {
    code: "PT",
    slug: "portugal",
    flag: "🇵🇹",
    name: {
      en: "Portugal",
      tr: "Portekiz",
      az: "Portuqaliya",
      ru: "Португалия",
      de: "Portugal",
      fr: "Portugal",
      fa: "پرتغال",
      ar: "البرتغال",
      tk: "Portugaliýa",
      kk: "Португалия",
      ky: "Португалия",
      zh: "葡萄牙",
      bg: "Португалия",
      ur: "پرتگال",
      uz: "Portugaliya",
      sw: "Ureno",
      so: "Bortuqaal",
      id: "Portugal",
    },
  },
  {
    code: "IE",
    slug: "ireland",
    flag: "🇮🇪",
    name: {
      en: "Ireland",
      tr: "İrlanda",
      az: "İrlandiya",
      ru: "Ирландия",
      de: "Irland",
      fr: "Irlande",
      fa: "ایرلند",
      ar: "أيرلندا",
      tk: "Irlandiýa",
      kk: "Ирландия",
      ky: "Ирландия",
      zh: "爱尔兰",
      bg: "Ирландия",
      ur: "آئرلینڈ",
      uz: "Irlandiya",
      sw: "Ayaland",
      so: "Ayrlaand",
      id: "Irlandia",
    },
  },
  {
    code: "CZ",
    slug: "czech-republic",
    flag: "🇨🇿",
    name: {
      en: "Czech Republic",
      tr: "Çekya",
      az: "Çexiya",
      ru: "Чехия",
      de: "Tschechien",
      fr: "Tchéquie",
      fa: "جمهوری چک",
      ar: "التشيك",
      tk: "Çehiýa",
      kk: "Чехия",
      ky: "Чехия",
      zh: "捷克",
      bg: "Чехия",
      ur: "چیک جمہوریہ",
      uz: "Chexiya",
      sw: "Ucheki",
      so: "Jekiya",
      id: "Ceko",
    },
  },
  {
    code: "HU",
    slug: "hungary",
    flag: "🇭🇺",
    name: {
      en: "Hungary",
      tr: "Macaristan",
      az: "Macarıstan",
      ru: "Венгрия",
      de: "Ungarn",
      fr: "Hongrie",
      fa: "مجارستان",
      ar: "المجر",
      tk: "Wengriýa",
      kk: "Венгрия",
      ky: "Венгрия",
      zh: "匈牙利",
      bg: "Унгария",
      ur: "ہنگری",
      uz: "Vengriya",
      sw: "Hungaria",
      so: "Hangari",
      id: "Hungaria",
    },
  },
  {
    code: "SK",
    slug: "slovakia",
    flag: "🇸🇰",
    name: {
      en: "Slovakia",
      tr: "Slovakya",
      az: "Slovakiya",
      ru: "Словакия",
      de: "Slowakei",
      fr: "Slovaquie",
      fa: "اسلواکی",
      ar: "سلوفاكيا",
      tk: "Slowakiýa",
      kk: "Словакия",
      ky: "Словакия",
      zh: "斯洛伐克",
      bg: "Словакия",
      ur: "سلوواکیہ",
      uz: "Slovakiya",
      sw: "Slovakia",
      so: "Slovakiya",
      id: "Slowakia",
    },
  },
  {
    code: "HR",
    slug: "croatia",
    flag: "🇭🇷",
    name: {
      en: "Croatia",
      tr: "Hırvatistan",
      az: "Xırvatıstan",
      ru: "Хорватия",
      de: "Kroatien",
      fr: "Croatie",
      fa: "کرواسی",
      ar: "كرواتيا",
      tk: "Horwatiýa",
      kk: "Хорватия",
      ky: "Хорватия",
      zh: "克罗地亚",
      bg: "Хърватия",
      ur: "کروشیا",
      uz: "Xorvatiya",
      sw: "Kroatia",
      so: "Korweesha",
      id: "Kroasia",
    },
  },
  {
    code: "RS",
    slug: "serbia",
    flag: "🇷🇸",
    name: {
      en: "Serbia",
      tr: "Sırbistan",
      az: "Serbiya",
      ru: "Сербия",
      de: "Serbien",
      fr: "Serbie",
      fa: "صربستان",
      ar: "صربيا",
      tk: "Serbiýa",
      kk: "Сербия",
      ky: "Сербия",
      zh: "塞尔维亚",
      bg: "Сърбия",
      ur: "سربیا",
      uz: "Serbiya",
      sw: "Serbia",
      so: "Seerbiya",
      id: "Serbia",
    },
  },
  {
    code: "BA",
    slug: "bosnia-and-herzegovina",
    flag: "🇧🇦",
    name: {
      en: "Bosnia and Herzegovina",
      tr: "Bosna-Hersek",
      az: "Bosniya və Herseqovina",
      ru: "Босния и Герцеговина",
      de: "Bosnien und Herzegowina",
      fr: "Bosnie-Herzégovine",
      fa: "بوسنی و هرزگوین",
      ar: "البوسنة والهرسك",
      tk: "Bosniýa we Gersegowina",
      kk: "Босния және Герцеговина",
      ky: "Босния жана Герцеговина",
      zh: "波斯尼亚和黑塞哥维那",
      bg: "Босна и Херцеговина",
      ur: "بوسنیا اور ہرزیگووینا",
      uz: "Bosniya va Gertsegovina",
      sw: "Bosnia na Herzegovina",
      so: "Boosniya iyo Herzegovina",
      id: "Bosnia dan Herzegovina",
    },
  },
  {
    code: "AL",
    slug: "albania",
    flag: "🇦🇱",
    name: {
      en: "Albania",
      tr: "Arnavutluk",
      az: "Albaniya",
      ru: "Албания",
      de: "Albanien",
      fr: "Albanie",
      fa: "آلبانی",
      ar: "ألبانيا",
      tk: "Albaniýa",
      kk: "Албания",
      ky: "Албания",
      zh: "阿尔巴尼亚",
      bg: "Албания",
      ur: "البانیہ",
      uz: "Albaniya",
      sw: "Albania",
      so: "Albaaniya",
      id: "Albania",
    },
  },
  {
    code: "MK",
    slug: "north-macedonia",
    flag: "🇲🇰",
    name: {
      en: "North Macedonia",
      tr: "Kuzey Makedonya",
      az: "Şimali Makedoniya",
      ru: "Северная Македония",
      de: "Nordmazedonien",
      fr: "Macédoine du Nord",
      fa: "مقدونیه شمالی",
      ar: "مقدونيا الشمالية",
      tk: "Demirgazyk Makedoniýa",
      kk: "Солтүстік Македония",
      ky: "Түндүк Македония",
      zh: "北马其顿",
      bg: "Северна Македония",
      ur: "شمالی مقدونیہ",
      uz: "Shimoliy Makedoniya",
      sw: "Makedonia Kaskazini",
      so: "Masedooniya Waqooyi",
      id: "Makedonia Utara",
    },
  },
  {
    code: "SI",
    slug: "slovenia",
    flag: "🇸🇮",
    name: {
      en: "Slovenia",
      tr: "Slovenya",
      az: "Sloveniya",
      ru: "Словения",
      de: "Slowenien",
      fr: "Slovénie",
      fa: "اسلوونی",
      ar: "سلوفينيا",
      tk: "Sloweniýa",
      kk: "Словения",
      ky: "Словения",
      zh: "斯洛文尼亚",
      bg: "Словения",
      ur: "سلووینیا",
      uz: "Sloveniya",
      sw: "Slovenia",
      so: "Sloveniya",
      id: "Slovenia",
    },
  },
  {
    code: "LT",
    slug: "lithuania",
    flag: "🇱🇹",
    name: {
      en: "Lithuania",
      tr: "Litvanya",
      az: "Litva",
      ru: "Литва",
      de: "Litauen",
      fr: "Lituanie",
      fa: "لیتوانی",
      ar: "ليتوانيا",
      tk: "Litwa",
      kk: "Литва",
      ky: "Литва",
      zh: "立陶宛",
      bg: "Литва",
      ur: "لتھوانیا",
      uz: "Litva",
      sw: "Lituania",
      so: "Lituweeniya",
      id: "Lituania",
    },
  },
  {
    code: "LV",
    slug: "latvia",
    flag: "🇱🇻",
    name: {
      en: "Latvia",
      tr: "Letonya",
      az: "Latviya",
      ru: "Латвия",
      de: "Lettland",
      fr: "Lettonie",
      fa: "لتونی",
      ar: "لاتفيا",
      tk: "Latwiýa",
      kk: "Латвия",
      ky: "Латвия",
      zh: "拉脱维亚",
      bg: "Латвия",
      ur: "لٹویا",
      uz: "Latviya",
      sw: "Latvia",
      so: "Latfiya",
      id: "Latvia",
    },
  },
  {
    code: "EE",
    slug: "estonia",
    flag: "🇪🇪",
    name: {
      en: "Estonia",
      tr: "Estonya",
      az: "Estoniya",
      ru: "Эстония",
      de: "Estland",
      fr: "Estonie",
      fa: "استونی",
      ar: "إستونيا",
      tk: "Estoniýa",
      kk: "Эстония",
      ky: "Эстония",
      zh: "爱沙尼亚",
      bg: "Естония",
      ur: "اسٹونیا",
      uz: "Estoniya",
      sw: "Estonia",
      so: "Estooniya",
      id: "Estonia",
    },
  },
  {
    code: "MD",
    slug: "moldova",
    flag: "🇲🇩",
    name: {
      en: "Moldova",
      tr: "Moldova",
      az: "Moldova",
      ru: "Молдова",
      de: "Moldau",
      fr: "Moldavie",
      fa: "مولداوی",
      ar: "مولدوفا",
      tk: "Moldowa",
      kk: "Молдова",
      ky: "Молдова",
      zh: "摩尔多瓦",
      bg: "Молдова",
      ur: "مالدووا",
      uz: "Moldova",
      sw: "Moldova",
      so: "Moldofa",
      id: "Moldova",
    },
  },
  {
    code: "GE",
    slug: "georgia",
    flag: "🇬🇪",
    name: {
      en: "Georgia",
      tr: "Gürcistan",
      az: "Gürcüstan",
      ru: "Грузия",
      de: "Georgien",
      fr: "Géorgie",
      fa: "گرجستان",
      ar: "جورجيا",
      tk: "Gruziýa",
      kk: "Грузия",
      ky: "Грузия",
      zh: "格鲁吉亚",
      bg: "Грузия",
      ur: "جارجیا",
      uz: "Gruziya",
      sw: "Jojia",
      so: "Joorjiya",
      id: "Georgia",
    },
  },
  {
    code: "AM",
    slug: "armenia",
    flag: "🇦🇲",
    name: {
      en: "Armenia",
      tr: "Ermenistan",
      az: "Ermənistan",
      ru: "Армения",
      de: "Armenien",
      fr: "Arménie",
      fa: "ارمنستان",
      ar: "أرمينيا",
      tk: "Ermenistan",
      kk: "Армения",
      ky: "Армения",
      zh: "亚美尼亚",
      bg: "Армения",
      ur: "آرمینیا",
      uz: "Armaniston",
      sw: "Armenia",
      so: "Armeeniya",
      id: "Armenia",
    },
  },
  {
    code: "IS",
    slug: "iceland",
    flag: "🇮🇸",
    name: {
      en: "Iceland",
      tr: "İzlanda",
      az: "İslandiya",
      ru: "Исландия",
      de: "Island",
      fr: "Islande",
      fa: "ایسلند",
      ar: "آيسلندا",
      tk: "Islandiýa",
      kk: "Исландия",
      ky: "Исландия",
      zh: "冰岛",
      bg: "Исландия",
      ur: "آئس لینڈ",
      uz: "Islandiya",
      sw: "Aisilandi",
      so: "Ayslaand",
      id: "Islandia",
    },
  },
  {
    code: "LU",
    slug: "luxembourg",
    flag: "🇱🇺",
    name: {
      en: "Luxembourg",
      tr: "Lüksemburg",
      az: "Lüksemburq",
      ru: "Люксембург",
      de: "Luxemburg",
      fr: "Luxembourg",
      fa: "لوکزامبورگ",
      ar: "لوكسمبورغ",
      tk: "Lýuksemburg",
      kk: "Люксембург",
      ky: "Люксембург",
      zh: "卢森堡",
      bg: "Люксембург",
      ur: "لکسمبرگ",
      uz: "Lyuksemburg",
      sw: "Lasembagi",
      so: "Luksemboorg",
      id: "Luksemburg",
    },
  },
  {
    code: "MT",
    slug: "malta",
    flag: "🇲🇹",
    name: {
      en: "Malta",
      tr: "Malta",
      az: "Malta",
      ru: "Мальта",
      de: "Malta",
      fr: "Malte",
      fa: "مالت",
      ar: "مالطا",
      tk: "Malta",
      kk: "Мальта",
      ky: "Мальта",
      zh: "马耳他",
      bg: "Малта",
      ur: "مالٹا",
      uz: "Malta",
      sw: "Malta",
      so: "Maalda",
      id: "Malta",
    },
  },
  {
    code: "CY",
    slug: "cyprus",
    flag: "🇨🇾",
    name: {
      en: "Cyprus",
      tr: "Kıbrıs",
      az: "Kipr",
      ru: "Кипр",
      de: "Zypern",
      fr: "Chypre",
      fa: "قبرص",
      ar: "قبرص",
      tk: "Kipr",
      kk: "Кипр",
      ky: "Кипр",
      zh: "塞浦路斯",
      bg: "Кипър",
      ur: "قبرص",
      uz: "Kipr",
      sw: "Kuprosi",
      so: "Qubrus",
      id: "Siprus",
    },
  },
  {
    code: "ME",
    slug: "montenegro",
    flag: "🇲🇪",
    name: {
      en: "Montenegro",
      tr: "Karadağ",
      az: "Çernoqoriya",
      ru: "Черногория",
      de: "Montenegro",
      fr: "Monténégro",
      fa: "مونتهنگرو",
      ar: "الجبل الأسود",
      tk: "Çernogoriýa",
      kk: "Черногория",
      ky: "Черногория",
      zh: "黑山",
      bg: "Черна гора",
      ur: "مونٹی نیگرو",
      uz: "Chernogoriya",
      sw: "Montenegro",
      so: "Montenegro",
      id: "Montenegro",
    },
  },

  // === Americas ===
  {
    code: "US",
    slug: "united-states",
    flag: "🇺🇸",
    name: {
      en: "United States",
      tr: "Amerika",
      az: "ABŞ",
      ru: "США",
      de: "Vereinigte Staaten",
      fr: "États-Unis",
      fa: "ایالات متحده",
      ar: "الولايات المتحدة",
      tk: "Amerikanyň Birleşen Ştatlary",
      kk: "АҚШ",
      ky: "АКШ",
      zh: "美国",
      bg: "САЩ",
      ur: "امریکہ",
      uz: "AQSh",
      sw: "Marekani",
      so: "Maraykanka",
      id: "Amerika Serikat",
    },
  },
  {
    code: "CA",
    slug: "canada",
    flag: "🇨🇦",
    name: {
      en: "Canada",
      tr: "Kanada",
      az: "Kanada",
      ru: "Канада",
      de: "Kanada",
      fr: "Canada",
      fa: "کانادا",
      ar: "كندا",
      tk: "Kanada",
      kk: "Канада",
      ky: "Канада",
      zh: "加拿大",
      bg: "Канада",
      ur: "کینیڈا",
      uz: "Kanada",
      sw: "Kanada",
      so: "Kanada",
      id: "Kanada",
    },
  },
  {
    code: "BR",
    slug: "brazil",
    flag: "🇧🇷",
    name: {
      en: "Brazil",
      tr: "Brezilya",
      az: "Braziliya",
      ru: "Бразилия",
      de: "Brasilien",
      fr: "Brésil",
      fa: "برزیل",
      ar: "البرازيل",
      tk: "Braziliýa",
      kk: "Бразилия",
      ky: "Бразилия",
      zh: "巴西",
      bg: "Бразилия",
      ur: "برازیل",
      uz: "Braziliya",
      sw: "Brazil",
      so: "Baraasiil",
      id: "Brasil",
    },
  },
  {
    code: "AR",
    slug: "argentina",
    flag: "🇦🇷",
    name: {
      en: "Argentina",
      tr: "Arjantin",
      az: "Argentina",
      ru: "Аргентина",
      de: "Argentinien",
      fr: "Argentine",
      fa: "آرژانتین",
      ar: "الأرجنتين",
      tk: "Argentinа",
      kk: "Аргентина",
      ky: "Аргентина",
      zh: "阿根廷",
      bg: "Аржентина",
      ur: "ارجنٹین",
      uz: "Argentina",
      sw: "Ajentina",
      so: "Arjantiin",
      id: "Argentina",
    },
  },
  {
    code: "MX",
    slug: "mexico",
    flag: "🇲🇽",
    name: {
      en: "Mexico",
      tr: "Meksika",
      az: "Meksika",
      ru: "Мексика",
      de: "Mexiko",
      fr: "Mexique",
      fa: "مکزیک",
      ar: "المكسيك",
      tk: "Meksika",
      kk: "Мексика",
      ky: "Мексика",
      zh: "墨西哥",
      bg: "Мексико",
      ur: "میکسیکو",
      uz: "Meksika",
      sw: "Meksiko",
      so: "Meksiko",
      id: "Meksiko",
    },
  },
  {
    code: "CO",
    slug: "colombia",
    flag: "🇨🇴",
    name: {
      en: "Colombia",
      tr: "Kolombiya",
      az: "Kolumbiya",
      ru: "Колумбия",
      de: "Kolumbien",
      fr: "Colombie",
      fa: "کلمبیا",
      ar: "كولومبيا",
      tk: "Kolumbiýa",
      kk: "Колумбия",
      ky: "Колумбия",
      zh: "哥伦比亚",
      bg: "Колумбия",
      ur: "کولمبیا",
      uz: "Kolumbiya",
      sw: "Kolombia",
      so: "Kolombiya",
      id: "Kolombia",
    },
  },
  {
    code: "CL",
    slug: "chile",
    flag: "🇨🇱",
    name: {
      en: "Chile",
      tr: "Şili",
      az: "Çili",
      ru: "Чили",
      de: "Chile",
      fr: "Chili",
      fa: "شیلی",
      ar: "تشيلي",
      tk: "Çili",
      kk: "Чили",
      ky: "Чили",
      zh: "智利",
      bg: "Чили",
      ur: "چلی",
      uz: "Chili",
      sw: "Chile",
      so: "Jili",
      id: "Chili",
    },
  },
  {
    code: "PE",
    slug: "peru",
    flag: "🇵🇪",
    name: {
      en: "Peru",
      tr: "Peru",
      az: "Peru",
      ru: "Перу",
      de: "Peru",
      fr: "Pérou",
      fa: "پرو",
      ar: "بيرو",
      tk: "Peru",
      kk: "Перу",
      ky: "Перу",
      zh: "秘鲁",
      bg: "Перу",
      ur: "پیرو",
      uz: "Peru",
      sw: "Peru",
      so: "Biru",
      id: "Peru",
    },
  },
  {
    code: "VE",
    slug: "venezuela",
    flag: "🇻🇪",
    name: {
      en: "Venezuela",
      tr: "Venezuela",
      az: "Venezuela",
      ru: "Венесуэла",
      de: "Venezuela",
      fr: "Venezuela",
      fa: "ونزوئلا",
      ar: "فنزويلا",
      tk: "Wenesuela",
      kk: "Венесуэла",
      ky: "Венесуэла",
      zh: "委内瑞拉",
      bg: "Венецуела",
      ur: "وینزویلا",
      uz: "Venesuela",
      sw: "Venezuela",
      so: "Fenesuwela",
      id: "Venezuela",
    },
  },
  {
    code: "EC",
    slug: "ecuador",
    flag: "🇪🇨",
    name: {
      en: "Ecuador",
      tr: "Ekvador",
      az: "Ekvador",
      ru: "Эквадор",
      de: "Ecuador",
      fr: "Équateur",
      fa: "اکوادور",
      ar: "الإكوادور",
      tk: "Ekwador",
      kk: "Эквадор",
      ky: "Эквадор",
      zh: "厄瓜多尔",
      bg: "Еквадор",
      ur: "ایکواڈور",
      uz: "Ekvador",
      sw: "Ekwado",
      so: "Ekuwador",
      id: "Ekuador",
    },
  },
  {
    code: "BO",
    slug: "bolivia",
    flag: "🇧🇴",
    name: {
      en: "Bolivia",
      tr: "Bolivya",
      az: "Boliviya",
      ru: "Боливия",
      de: "Bolivien",
      fr: "Bolivie",
      fa: "بولیوی",
      ar: "بوليفيا",
      tk: "Boliwiýa",
      kk: "Боливия",
      ky: "Боливия",
      zh: "玻利维亚",
      bg: "Боливия",
      ur: "بولیویا",
      uz: "Boliviya",
      sw: "Bolivia",
      so: "Boliifiya",
      id: "Bolivia",
    },
  },
  {
    code: "PY",
    slug: "paraguay",
    flag: "🇵🇾",
    name: {
      en: "Paraguay",
      tr: "Paraguay",
      az: "Paraqvay",
      ru: "Парагвай",
      de: "Paraguay",
      fr: "Paraguay",
      fa: "پاراگوئه",
      ar: "باراغواي",
      tk: "Paragwaý",
      kk: "Парагвай",
      ky: "Парагвай",
      zh: "巴拉圭",
      bg: "Парагвай",
      ur: "پیراگوئے",
      uz: "Paragvay",
      sw: "Paraguay",
      so: "Baragwai",
      id: "Paraguay",
    },
  },
  {
    code: "UY",
    slug: "uruguay",
    flag: "🇺🇾",
    name: {
      en: "Uruguay",
      tr: "Uruguay",
      az: "Uruqvay",
      ru: "Уругвай",
      de: "Uruguay",
      fr: "Uruguay",
      fa: "اروگوئه",
      ar: "أوروغواي",
      tk: "Urugwaý",
      kk: "Уругвай",
      ky: "Уругвай",
      zh: "乌拉圭",
      bg: "Уругвай",
      ur: "یوراگوئے",
      uz: "Urugvay",
      sw: "Uruguay",
      so: "Urugway",
      id: "Uruguay",
    },
  },
  {
    code: "CR",
    slug: "costa-rica",
    flag: "🇨🇷",
    name: {
      en: "Costa Rica",
      tr: "Kosta Rika",
      az: "Kosta Rika",
      ru: "Коста-Рика",
      de: "Costa Rica",
      fr: "Costa Rica",
      fa: "کاستاریکا",
      ar: "كوستاريكا",
      tk: "Kosta-Rika",
      kk: "Коста-Рика",
      ky: "Коста-Рика",
      zh: "哥斯达黎加",
      bg: "Коста Рика",
      ur: "کوسٹا ریکا",
      uz: "Kosta-Rika",
      sw: "Kosta Rika",
      so: "Kosta Riika",
      id: "Kosta Rika",
    },
  },
  {
    code: "PA",
    slug: "panama",
    flag: "🇵🇦",
    name: {
      en: "Panama",
      tr: "Panama",
      az: "Panama",
      ru: "Панама",
      de: "Panama",
      fr: "Panama",
      fa: "پاناما",
      ar: "بنما",
      tk: "Panama",
      kk: "Панама",
      ky: "Панама",
      zh: "巴拿马",
      bg: "Панама",
      ur: "پاناما",
      uz: "Panama",
      sw: "Panama",
      so: "Bannama",
      id: "Panama",
    },
  },
  {
    code: "DO",
    slug: "dominican-republic",
    flag: "🇩🇴",
    name: {
      en: "Dominican Republic",
      tr: "Dominik Cumhuriyeti",
      az: "Dominikan Respublikası",
      ru: "Доминиканская Республика",
      de: "Dominikanische Republik",
      fr: "République dominicaine",
      fa: "جمهوری دومینیکن",
      ar: "جمهورية الدومينيكان",
      tk: "Dominikan Respublikasy",
      kk: "Доминикан Республикасы",
      ky: "Доминикан Республикасы",
      zh: "多米尼加共和国",
      bg: "Доминиканска република",
      ur: "ڈومینیکن ریپبلک",
      uz: "Dominikan Respublikasi",
      sw: "Jamhuri ya Dominika",
      so: "Jamhuuriyadda Dominika",
      id: "Republik Dominika",
    },
  },
  {
    code: "GT",
    slug: "guatemala",
    flag: "🇬🇹",
    name: {
      en: "Guatemala",
      tr: "Guatemala",
      az: "Qvatemala",
      ru: "Гватемала",
      de: "Guatemala",
      fr: "Guatemala",
      fa: "گواتمالا",
      ar: "غواتيمالا",
      tk: "Gwatemala",
      kk: "Гватемала",
      ky: "Гватемала",
      zh: "危地马拉",
      bg: "Гватемала",
      ur: "گوئٹے مالا",
      uz: "Gvatemala",
      sw: "Guatemala",
      so: "Guwaatemaala",
      id: "Guatemala",
    },
  },
  {
    code: "HN",
    slug: "honduras",
    flag: "🇭🇳",
    name: {
      en: "Honduras",
      tr: "Honduras",
      az: "Honduras",
      ru: "Гондурас",
      de: "Honduras",
      fr: "Honduras",
      fa: "هندوراس",
      ar: "هندوراس",
      tk: "Gonduras",
      kk: "Гондурас",
      ky: "Гондурас",
      zh: "洪都拉斯",
      bg: "Хондурас",
      ur: "ہونڈوراس",
      uz: "Gonduras",
      sw: "Honduras",
      so: "Honduras",
      id: "Honduras",
    },
  },
  {
    code: "SV",
    slug: "el-salvador",
    flag: "🇸🇻",
    name: {
      en: "El Salvador",
      tr: "El Salvador",
      az: "El Salvador",
      ru: "Сальвадор",
      de: "El Salvador",
      fr: "El Salvador",
      fa: "السالوادور",
      ar: "السلفادور",
      tk: "El Salwador",
      kk: "Сальвадор",
      ky: "Сальвадор",
      zh: "萨尔瓦多",
      bg: "Ел Салвадор",
      ur: "ال سلواڈور",
      uz: "El Salvador",
      sw: "El Salvador",
      so: "El Salfador",
      id: "El Salvador",
    },
  },
  {
    code: "NI",
    slug: "nicaragua",
    flag: "🇳🇮",
    name: {
      en: "Nicaragua",
      tr: "Nikaragua",
      az: "Nikaraqua",
      ru: "Никарагуа",
      de: "Nicaragua",
      fr: "Nicaragua",
      fa: "نیکاراگوئه",
      ar: "نيكاراغوا",
      tk: "Nikaragua",
      kk: "Никарагуа",
      ky: "Никарагуа",
      zh: "尼加拉瓜",
      bg: "Никарагуа",
      ur: "نکاراگوا",
      uz: "Nikaragua",
      sw: "Nikaragua",
      so: "Nikaraaguwa",
      id: "Nikaragua",
    },
  },
  {
    code: "CU",
    slug: "cuba",
    flag: "🇨🇺",
    name: {
      en: "Cuba",
      tr: "Küba",
      az: "Kuba",
      ru: "Куба",
      de: "Kuba",
      fr: "Cuba",
      fa: "کوبا",
      ar: "كوبا",
      tk: "Kuba",
      kk: "Куба",
      ky: "Куба",
      zh: "古巴",
      bg: "Куба",
      ur: "کیوبا",
      uz: "Kuba",
      sw: "Kuba",
      so: "Kuuba",
      id: "Kuba",
    },
  },
  {
    code: "HT",
    slug: "haiti",
    flag: "🇭🇹",
    name: {
      en: "Haiti",
      tr: "Haiti",
      az: "Haiti",
      ru: "Гаити",
      de: "Haiti",
      fr: "Haïti",
      fa: "هائیتی",
      ar: "هايتي",
      tk: "Gaiti",
      kk: "Гаити",
      ky: "Гаити",
      zh: "海地",
      bg: "Хаити",
      ur: "ہیٹی",
      uz: "Gaiti",
      sw: "Haiti",
      so: "Haiti",
      id: "Haiti",
    },
  },
  {
    code: "JM",
    slug: "jamaica",
    flag: "🇯🇲",
    name: {
      en: "Jamaica",
      tr: "Jamaika",
      az: "Yamayka",
      ru: "Ямайка",
      de: "Jamaika",
      fr: "Jamaïque",
      fa: "جامائیکا",
      ar: "جامايكا",
      tk: "Ýamaýka",
      kk: "Ямайка",
      ky: "Ямайка",
      zh: "牙买加",
      bg: "Ямайка",
      ur: "جمیکا",
      uz: "Yamayka",
      sw: "Jamaika",
      so: "Jamayka",
      id: "Jamaika",
    },
  },
  {
    code: "TT",
    slug: "trinidad-and-tobago",
    flag: "🇹🇹",
    name: {
      en: "Trinidad and Tobago",
      tr: "Trinidad ve Tobago",
      az: "Trinidad və Tobaqo",
      ru: "Тринидад и Тобаго",
      de: "Trinidad und Tobago",
      fr: "Trinité-et-Tobago",
      fa: "ترینیداد و توباگو",
      ar: "ترينيداد وتوباغو",
      tk: "Trinidad we Tobago",
      kk: "Тринидад және Тобаго",
      ky: "Тринидад жана Тобаго",
      zh: "特立尼达和多巴哥",
      bg: "Тринидад и Тобаго",
      ur: "ٹرینیڈاڈ اور ٹوباگو",
      uz: "Trinidad va Tobago",
      sw: "Trinidad na Tobago",
      so: "Trinidaad iyo Tobago",
      id: "Trinidad dan Tobago",
    },
  },

  // === Asia ===
  {
    code: "CN",
    slug: "china",
    flag: "🇨🇳",
    name: {
      en: "China",
      tr: "Çin",
      az: "Çin",
      ru: "Китай",
      de: "China",
      fr: "Chine",
      fa: "چین",
      ar: "الصين",
      tk: "Hytaý",
      kk: "Қытай",
      ky: "Кытай",
      zh: "中国",
      bg: "Китай",
      ur: "چین",
      uz: "Xitoy",
      sw: "China",
      so: "Shiinaha",
      id: "Tiongkok",
    },
  },
  {
    code: "IN",
    slug: "india",
    flag: "🇮🇳",
    name: {
      en: "India",
      tr: "Hindistan",
      az: "Hindistan",
      ru: "Индия",
      de: "Indien",
      fr: "Inde",
      fa: "هند",
      ar: "الهند",
      tk: "Hindistan",
      kk: "Үндістан",
      ky: "Индия",
      zh: "印度",
      bg: "Индия",
      ur: "بھارت",
      uz: "Hindiston",
      sw: "India",
      so: "Hindiya",
      id: "India",
    },
  },
  {
    code: "JP",
    slug: "japan",
    flag: "🇯🇵",
    name: {
      en: "Japan",
      tr: "Japonya",
      az: "Yaponiya",
      ru: "Япония",
      de: "Japan",
      fr: "Japon",
      fa: "ژاپن",
      ar: "اليابان",
      tk: "Ýaponiýa",
      kk: "Жапония",
      ky: "Жапония",
      zh: "日本",
      bg: "Япония",
      ur: "جاپان",
      uz: "Yaponiya",
      sw: "Japani",
      so: "Jabbaan",
      id: "Jepang",
    },
  },
  {
    code: "KR",
    slug: "south-korea",
    flag: "🇰🇷",
    name: {
      en: "South Korea",
      tr: "Güney Kore",
      az: "Cənubi Koreya",
      ru: "Южная Корея",
      de: "Südkorea",
      fr: "Corée du Sud",
      fa: "کره جنوبی",
      ar: "كوريا الجنوبية",
      tk: "Günorta Koreýa",
      kk: "Оңтүстік Корея",
      ky: "Түштүк Корея",
      zh: "韩国",
      bg: "Южна Корея",
      ur: "جنوبی کوریا",
      uz: "Janubiy Koreya",
      sw: "Korea Kusini",
      so: "Kuuriya Koonfureed",
      id: "Korea Selatan",
    },
  },
  {
    code: "ID",
    slug: "indonesia",
    flag: "🇮🇩",
    name: {
      en: "Indonesia",
      tr: "Endonezya",
      az: "İndoneziya",
      ru: "Индонезия",
      de: "Indonesien",
      fr: "Indonésie",
      fa: "اندونزی",
      ar: "إندونيسيا",
      tk: "Indoneziýa",
      kk: "Индонезия",
      ky: "Индонезия",
      zh: "印度尼西亚",
      bg: "Индонезия",
      ur: "انڈونیشیا",
      uz: "Indoneziya",
      sw: "Indonesia",
      so: "Indoneesiya",
      id: "Indonesia",
    },
  },
  {
    code: "MY",
    slug: "malaysia",
    flag: "🇲🇾",
    name: {
      en: "Malaysia",
      tr: "Malezya",
      az: "Malayziya",
      ru: "Малайзия",
      de: "Malaysia",
      fr: "Malaisie",
      fa: "مالزی",
      ar: "ماليزيا",
      tk: "Malaýziýa",
      kk: "Малайзия",
      ky: "Малайзия",
      zh: "马来西亚",
      bg: "Малайзия",
      ur: "ملائیشیا",
      uz: "Malayziya",
      sw: "Malaysia",
      so: "Malaysiya",
      id: "Malaysia",
    },
  },
  {
    code: "TH",
    slug: "thailand",
    flag: "🇹🇭",
    name: {
      en: "Thailand",
      tr: "Tayland",
      az: "Tailand",
      ru: "Таиланд",
      de: "Thailand",
      fr: "Thaïlande",
      fa: "تایلند",
      ar: "تايلاند",
      tk: "Taýland",
      kk: "Тайланд",
      ky: "Тайланд",
      zh: "泰国",
      bg: "Тайланд",
      ur: "تھائی لینڈ",
      uz: "Tailand",
      sw: "Thailand",
      so: "Tayland",
      id: "Thailand",
    },
  },
  {
    code: "VN",
    slug: "vietnam",
    flag: "🇻🇳",
    name: {
      en: "Vietnam",
      tr: "Vietnam",
      az: "Vyetnam",
      ru: "Вьетнам",
      de: "Vietnam",
      fr: "Viêt Nam",
      fa: "ویتنام",
      ar: "فيتنام",
      tk: "Wýetnam",
      kk: "Вьетнам",
      ky: "Вьетнам",
      zh: "越南",
      bg: "Виетнам",
      ur: "ویتنام",
      uz: "Vyetnam",
      sw: "Vietnam",
      so: "Fiyetnaam",
      id: "Vietnam",
    },
  },
  {
    code: "PH",
    slug: "philippines",
    flag: "🇵🇭",
    name: {
      en: "Philippines",
      tr: "Filipinler",
      az: "Filippin",
      ru: "Филиппины",
      de: "Philippinen",
      fr: "Philippines",
      fa: "فیلیپین",
      ar: "الفلبين",
      tk: "Filippinler",
      kk: "Филиппин",
      ky: "Филиппин",
      zh: "菲律宾",
      bg: "Филипини",
      ur: "فلپائن",
      uz: "Filippin",
      sw: "Filipino",
      so: "Filibiin",
      id: "Filipina",
    },
  },
  {
    code: "SG",
    slug: "singapore",
    flag: "🇸🇬",
    name: {
      en: "Singapore",
      tr: "Singapur",
      az: "Sinqapur",
      ru: "Сингапур",
      de: "Singapur",
      fr: "Singapour",
      fa: "سنگاپور",
      ar: "سنغافورة",
      tk: "Singapur",
      kk: "Сингапур",
      ky: "Сингапур",
      zh: "新加坡",
      bg: "Сингапур",
      ur: "سنگاپور",
      uz: "Singapur",
      sw: "Singapore",
      so: "Singabuur",
      id: "Singapura",
    },
  },
  {
    code: "BD",
    slug: "bangladesh",
    flag: "🇧🇩",
    name: {
      en: "Bangladesh",
      tr: "Bangladeş",
      az: "Banqladeş",
      ru: "Бангладеш",
      de: "Bangladesch",
      fr: "Bangladesh",
      fa: "بنگلادش",
      ar: "بنغلاديش",
      tk: "Bangladeş",
      kk: "Бангладеш",
      ky: "Бангладеш",
      zh: "孟加拉国",
      bg: "Бангладеш",
      ur: "بنگلہ دیش",
      uz: "Bangladesh",
      sw: "Bangladeshi",
      so: "Bangaaladheesh",
      id: "Bangladesh",
    },
  },
  {
    code: "LK",
    slug: "sri-lanka",
    flag: "🇱🇰",
    name: {
      en: "Sri Lanka",
      tr: "Sri Lanka",
      az: "Şri-Lanka",
      ru: "Шри-Ланка",
      de: "Sri Lanka",
      fr: "Sri Lanka",
      fa: "سریلانکا",
      ar: "سريلانكا",
      tk: "Şri-Lanka",
      kk: "Шри-Ланка",
      ky: "Шри-Ланка",
      zh: "斯里兰卡",
      bg: "Шри Ланка",
      ur: "سری لنکا",
      uz: "Shri-Lanka",
      sw: "Sri Lanka",
      so: "Siri Laanka",
      id: "Sri Lanka",
    },
  },
  {
    code: "NP",
    slug: "nepal",
    flag: "🇳🇵",
    name: {
      en: "Nepal",
      tr: "Nepal",
      az: "Nepal",
      ru: "Непал",
      de: "Nepal",
      fr: "Népal",
      fa: "نپال",
      ar: "نيبال",
      tk: "Nepal",
      kk: "Непал",
      ky: "Непал",
      zh: "尼泊尔",
      bg: "Непал",
      ur: "نیپال",
      uz: "Nepal",
      sw: "Nepali",
      so: "Nebaal",
      id: "Nepal",
    },
  },
  {
    code: "AF",
    slug: "afghanistan",
    flag: "🇦🇫",
    name: {
      en: "Afghanistan",
      tr: "Afganistan",
      az: "Əfqanıstan",
      ru: "Афганистан",
      de: "Afghanistan",
      fr: "Afghanistan",
      fa: "افغانستان",
      ar: "أفغانستان",
      tk: "Owganystan",
      kk: "Ауғанстан",
      ky: "Ооганстан",
      zh: "阿富汗",
      bg: "Афганистан",
      ur: "افغانستان",
      uz: "Afgʻoniston",
      sw: "Afghanistan",
      so: "Afgaanistaan",
      id: "Afganistan",
    },
  },
  {
    code: "SA",
    slug: "saudi-arabia",
    flag: "🇸🇦",
    name: {
      en: "Saudi Arabia",
      tr: "Suudi Arabistan",
      az: "Səudiyyə Ərəbistanı",
      ru: "Саудовская Аравия",
      de: "Saudi-Arabien",
      fr: "Arabie saoudite",
      fa: "عربستان سعودی",
      ar: "السعودية",
      tk: "Saud Arabystany",
      kk: "Сауд Арабиясы",
      ky: "Сауд Арабиясы",
      zh: "沙特阿拉伯",
      bg: "Саудитска Арабия",
      ur: "سعودی عرب",
      uz: "Saudiya Arabistoni",
      sw: "Saudi Arabia",
      so: "Sacuudi Carabiya",
      id: "Arab Saudi",
    },
  },
  {
    code: "AE",
    slug: "united-arab-emirates",
    flag: "🇦🇪",
    name: {
      en: "United Arab Emirates",
      tr: "BAE",
      az: "BƏE",
      ru: "ОАЭ",
      de: "Vereinigte Arabische Emirate",
      fr: "Émirats arabes unis",
      fa: "امارات متحده عربی",
      ar: "الإمارات",
      tk: "BAE",
      kk: "БАӘ",
      ky: "БАЭ",
      zh: "阿联酋",
      bg: "ОАЕ",
      ur: "متحدہ عرب امارات",
      uz: "BAA",
      sw: "UAE",
      so: "Imaaraadka Carabta",
      id: "Uni Emirat Arab",
    },
  },
  {
    code: "QA",
    slug: "qatar",
    flag: "🇶🇦",
    name: {
      en: "Qatar",
      tr: "Katar",
      az: "Qətər",
      ru: "Катар",
      de: "Katar",
      fr: "Qatar",
      fa: "قطر",
      ar: "قطر",
      tk: "Katar",
      kk: "Катар",
      ky: "Катар",
      zh: "卡塔尔",
      bg: "Катар",
      ur: "قطر",
      uz: "Qatar",
      sw: "Qatar",
      so: "Qadar",
      id: "Qatar",
    },
  },
  {
    code: "KW",
    slug: "kuwait",
    flag: "🇰🇼",
    name: {
      en: "Kuwait",
      tr: "Kuveyt",
      az: "Küveyt",
      ru: "Кувейт",
      de: "Kuwait",
      fr: "Koweït",
      fa: "کویت",
      ar: "الكويت",
      tk: "Kuweýt",
      kk: "Кувейт",
      ky: "Кувейт",
      zh: "科威特",
      bg: "Кувейт",
      ur: "کویت",
      uz: "Quvayt",
      sw: "Kuwait",
      so: "Kuwayt",
      id: "Kuwait",
    },
  },
  {
    code: "BH",
    slug: "bahrain",
    flag: "🇧🇭",
    name: {
      en: "Bahrain",
      tr: "Bahreyn",
      az: "Bəhreyn",
      ru: "Бахрейн",
      de: "Bahrain",
      fr: "Bahreïn",
      fa: "بحرین",
      ar: "البحرين",
      tk: "Bahreýn",
      kk: "Бахрейн",
      ky: "Бахрейн",
      zh: "巴林",
      bg: "Бахрейн",
      ur: "بحرین",
      uz: "Bahrayn",
      sw: "Bahrain",
      so: "Baxrayn",
      id: "Bahrain",
    },
  },
  {
    code: "OM",
    slug: "oman",
    flag: "🇴🇲",
    name: {
      en: "Oman",
      tr: "Umman",
      az: "Oman",
      ru: "Оман",
      de: "Oman",
      fr: "Oman",
      fa: "عمان",
      ar: "عمان",
      tk: "Oman",
      kk: "Оман",
      ky: "Оман",
      zh: "阿曼",
      bg: "Оман",
      ur: "عمان",
      uz: "Ummon",
      sw: "Omani",
      so: "Cumaan",
      id: "Oman",
    },
  },
  {
    code: "JO",
    slug: "jordan",
    flag: "🇯🇴",
    name: {
      en: "Jordan",
      tr: "Ürdün",
      az: "İordaniya",
      ru: "Иордания",
      de: "Jordanien",
      fr: "Jordanie",
      fa: "اردن",
      ar: "الأردن",
      tk: "Iordaniýa",
      kk: "Иордания",
      ky: "Иордания",
      zh: "约旦",
      bg: "Йордания",
      ur: "اردن",
      uz: "Iordaniya",
      sw: "Yordani",
      so: "Urdun",
      id: "Yordania",
    },
  },
  {
    code: "LB",
    slug: "lebanon",
    flag: "🇱🇧",
    name: {
      en: "Lebanon",
      tr: "Lübnan",
      az: "Livan",
      ru: "Ливан",
      de: "Libanon",
      fr: "Liban",
      fa: "لبنان",
      ar: "لبنان",
      tk: "Liwan",
      kk: "Ливан",
      ky: "Ливан",
      zh: "黎巴嫩",
      bg: "Ливан",
      ur: "لبنان",
      uz: "Livan",
      sw: "Lebanon",
      so: "Lubnaan",
      id: "Lebanon",
    },
  },
  {
    code: "SY",
    slug: "syria",
    flag: "🇸🇾",
    name: {
      en: "Syria",
      tr: "Suriye",
      az: "Suriya",
      ru: "Сирия",
      de: "Syrien",
      fr: "Syrie",
      fa: "سوریه",
      ar: "سوريا",
      tk: "Siriýa",
      kk: "Сирия",
      ky: "Сирия",
      zh: "叙利亚",
      bg: "Сирия",
      ur: "شام",
      uz: "Suriya",
      sw: "Siria",
      so: "Suuriya",
      id: "Suriah",
    },
  },
  {
    code: "PS",
    slug: "palestine",
    flag: "🇵🇸",
    name: {
      en: "Palestine",
      tr: "Filistin",
      az: "Fələstin",
      ru: "Палестина",
      de: "Palästina",
      fr: "Palestine",
      fa: "فلسطین",
      ar: "فلسطين",
      tk: "Palestina",
      kk: "Палестина",
      ky: "Палестина",
      zh: "巴勒斯坦",
      bg: "Палестина",
      ur: "فلسطین",
      uz: "Falastin",
      sw: "Palestina",
      so: "Falastiin",
      id: "Palestina",
    },
  },
  {
    code: "YE",
    slug: "yemen",
    flag: "🇾🇪",
    name: {
      en: "Yemen",
      tr: "Yemen",
      az: "Yəmən",
      ru: "Йемен",
      de: "Jemen",
      fr: "Yémen",
      fa: "یمن",
      ar: "اليمن",
      tk: "Ýemen",
      kk: "Йемен",
      ky: "Йемен",
      zh: "也门",
      bg: "Йемен",
      ur: "یمن",
      uz: "Yaman",
      sw: "Yemen",
      so: "Yaman",
      id: "Yaman",
    },
  },
  {
    code: "MM",
    slug: "myanmar",
    flag: "🇲🇲",
    name: {
      en: "Myanmar",
      tr: "Myanmar",
      az: "Myanma",
      ru: "Мьянма",
      de: "Myanmar",
      fr: "Myanmar",
      fa: "میانمار",
      ar: "ميانمار",
      tk: "Mýanma",
      kk: "Мьянма",
      ky: "Мьянма",
      zh: "缅甸",
      bg: "Мианмар",
      ur: "میانمار",
      uz: "Myanma",
      sw: "Myanmar",
      so: "Mayanmaar",
      id: "Myanmar",
    },
  },
  {
    code: "KH",
    slug: "cambodia",
    flag: "🇰🇭",
    name: {
      en: "Cambodia",
      tr: "Kamboçya",
      az: "Kamboca",
      ru: "Камбоджа",
      de: "Kambodscha",
      fr: "Cambodge",
      fa: "کامبوج",
      ar: "كمبوديا",
      tk: "Kamboja",
      kk: "Камбоджа",
      ky: "Камбоджа",
      zh: "柬埔寨",
      bg: "Камбоджа",
      ur: "کمبوڈیا",
      uz: "Kambodja",
      sw: "Kambodia",
      so: "Kamboodiya",
      id: "Kamboja",
    },
  },
  {
    code: "LA",
    slug: "laos",
    flag: "🇱🇦",
    name: {
      en: "Laos",
      tr: "Laos",
      az: "Laos",
      ru: "Лаос",
      de: "Laos",
      fr: "Laos",
      fa: "لائوس",
      ar: "لاوس",
      tk: "Laos",
      kk: "Лаос",
      ky: "Лаос",
      zh: "老挝",
      bg: "Лаос",
      ur: "لاؤس",
      uz: "Laos",
      sw: "Laos",
      so: "Laos",
      id: "Laos",
    },
  },
  {
    code: "MN",
    slug: "mongolia",
    flag: "🇲🇳",
    name: {
      en: "Mongolia",
      tr: "Moğolistan",
      az: "Monqolustan",
      ru: "Монголия",
      de: "Mongolei",
      fr: "Mongolie",
      fa: "مغولستان",
      ar: "منغوليا",
      tk: "Mongoliýa",
      kk: "Моңғолия",
      ky: "Монголия",
      zh: "蒙古",
      bg: "Монголия",
      ur: "منگولیا",
      uz: "Mongoliya",
      sw: "Mongolia",
      so: "Mongooliya",
      id: "Mongolia",
    },
  },
  {
    code: "TW",
    slug: "taiwan",
    flag: "🇹🇼",
    name: {
      en: "Taiwan",
      tr: "Tayvan",
      az: "Tayvan",
      ru: "Тайвань",
      de: "Taiwan",
      fr: "Taïwan",
      fa: "تایوان",
      ar: "تايوان",
      tk: "Taýwan",
      kk: "Тайвань",
      ky: "Тайвань",
      zh: "台湾",
      bg: "Тайван",
      ur: "تائیوان",
      uz: "Tayvan",
      sw: "Taiwan",
      so: "Taywaan",
      id: "Taiwan",
    },
  },
  {
    code: "HK",
    slug: "hong-kong",
    flag: "🇭🇰",
    name: {
      en: "Hong Kong",
      tr: "Hong Kong",
      az: "Honq Konq",
      ru: "Гонконг",
      de: "Hongkong",
      fr: "Hong Kong",
      fa: "هنگ کنگ",
      ar: "هونغ كونغ",
      tk: "Gonkong",
      kk: "Гонконг",
      ky: "Гонконг",
      zh: "香港",
      bg: "Хонконг",
      ur: "ہانگ کانگ",
      uz: "Gonkong",
      sw: "Hong Kong",
      so: "Hong Kong",
      id: "Hong Kong",
    },
  },

  // === Africa ===
  {
    code: "EG",
    slug: "egypt",
    flag: "🇪🇬",
    name: {
      en: "Egypt",
      tr: "Mısır",
      az: "Misir",
      ru: "Египет",
      de: "Ägypten",
      fr: "Égypte",
      fa: "مصر",
      ar: "مصر",
      tk: "Müsür",
      kk: "Мысыр",
      ky: "Мысыр",
      zh: "埃及",
      bg: "Египет",
      ur: "مصر",
      uz: "Misr",
      sw: "Misri",
      so: "Masar",
      id: "Mesir",
    },
  },
  {
    code: "MA",
    slug: "morocco",
    flag: "🇲🇦",
    name: {
      en: "Morocco",
      tr: "Fas",
      az: "Mərakeş",
      ru: "Марокко",
      de: "Marokko",
      fr: "Maroc",
      fa: "مراکش",
      ar: "المغرب",
      tk: "Marokko",
      kk: "Марокко",
      ky: "Марокко",
      zh: "摩洛哥",
      bg: "Мароко",
      ur: "مراکش",
      uz: "Marokash",
      sw: "Moroko",
      so: "Marooko",
      id: "Maroko",
    },
  },
  {
    code: "DZ",
    slug: "algeria",
    flag: "🇩🇿",
    name: {
      en: "Algeria",
      tr: "Cezayir",
      az: "Əlcəzair",
      ru: "Алжир",
      de: "Algerien",
      fr: "Algérie",
      fa: "الجزایر",
      ar: "الجزائر",
      tk: "Alžir",
      kk: "Алжир",
      ky: "Алжир",
      zh: "阿尔及利亚",
      bg: "Алжир",
      ur: "الجیریا",
      uz: "Jazoir",
      sw: "Aljeria",
      so: "Aljeeriya",
      id: "Aljazair",
    },
  },
  {
    code: "TN",
    slug: "tunisia",
    flag: "🇹🇳",
    name: {
      en: "Tunisia",
      tr: "Tunus",
      az: "Tunis",
      ru: "Тунис",
      de: "Tunesien",
      fr: "Tunisie",
      fa: "تونس",
      ar: "تونس",
      tk: "Tunis",
      kk: "Тунис",
      ky: "Тунис",
      zh: "突尼斯",
      bg: "Тунис",
      ur: "تونس",
      uz: "Tunis",
      sw: "Tunisia",
      so: "Tuniisiya",
      id: "Tunisia",
    },
  },
  {
    code: "LY",
    slug: "libya",
    flag: "🇱🇾",
    name: {
      en: "Libya",
      tr: "Libya",
      az: "Liviya",
      ru: "Ливия",
      de: "Libyen",
      fr: "Libye",
      fa: "لیبی",
      ar: "ليبيا",
      tk: "Liwiýa",
      kk: "Ливия",
      ky: "Ливия",
      zh: "利比亚",
      bg: "Либия",
      ur: "لیبیا",
      uz: "Liviya",
      sw: "Libya",
      so: "Liibiya",
      id: "Libya",
    },
  },
  {
    code: "SD",
    slug: "sudan",
    flag: "🇸🇩",
    name: {
      en: "Sudan",
      tr: "Sudan",
      az: "Sudan",
      ru: "Судан",
      de: "Sudan",
      fr: "Soudan",
      fa: "سودان",
      ar: "السودان",
      tk: "Sudan",
      kk: "Судан",
      ky: "Судан",
      zh: "苏丹",
      bg: "Судан",
      ur: "سوڈان",
      uz: "Sudan",
      sw: "Sudani",
      so: "Suudaan",
      id: "Sudan",
    },
  },
  {
    code: "ET",
    slug: "ethiopia",
    flag: "🇪🇹",
    name: {
      en: "Ethiopia",
      tr: "Etiyopya",
      az: "Efiopiya",
      ru: "Эфиопия",
      de: "Äthiopien",
      fr: "Éthiopie",
      fa: "اتیوپی",
      ar: "إثيوبيا",
      tk: "Efiopiýa",
      kk: "Эфиопия",
      ky: "Эфиопия",
      zh: "埃塞俄比亚",
      bg: "Етиопия",
      ur: "ایتھوپیا",
      uz: "Efiopiya",
      sw: "Ethiopia",
      so: "Itoobiya",
      id: "Etiopia",
    },
  },
  {
    code: "KE",
    slug: "kenya",
    flag: "🇰🇪",
    name: {
      en: "Kenya",
      tr: "Kenya",
      az: "Keniya",
      ru: "Кения",
      de: "Kenia",
      fr: "Kenya",
      fa: "کنیا",
      ar: "كينيا",
      tk: "Keniýa",
      kk: "Кения",
      ky: "Кения",
      zh: "肯尼亚",
      bg: "Кения",
      ur: "کینیا",
      uz: "Keniya",
      sw: "Kenya",
      so: "Kenya",
      id: "Kenya",
    },
  },
  {
    code: "TZ",
    slug: "tanzania",
    flag: "🇹🇿",
    name: {
      en: "Tanzania",
      tr: "Tanzanya",
      az: "Tanzaniya",
      ru: "Танзания",
      de: "Tansania",
      fr: "Tanzanie",
      fa: "تانزانیا",
      ar: "تنزانيا",
      tk: "Tanzaniýa",
      kk: "Танзания",
      ky: "Танзания",
      zh: "坦桑尼亚",
      bg: "Танзания",
      ur: "تنزانیہ",
      uz: "Tanzaniya",
      sw: "Tanzania",
      so: "Tansaaniya",
      id: "Tanzania",
    },
  },
  {
    code: "UG",
    slug: "uganda",
    flag: "🇺🇬",
    name: {
      en: "Uganda",
      tr: "Uganda",
      az: "Uqanda",
      ru: "Уганда",
      de: "Uganda",
      fr: "Ouganda",
      fa: "اوگاندا",
      ar: "أوغندا",
      tk: "Uganda",
      kk: "Уганда",
      ky: "Уганда",
      zh: "乌干达",
      bg: "Уганда",
      ur: "یوگنڈا",
      uz: "Uganda",
      sw: "Uganda",
      so: "Ugaanda",
      id: "Uganda",
    },
  },
  {
    code: "GH",
    slug: "ghana",
    flag: "🇬🇭",
    name: {
      en: "Ghana",
      tr: "Gana",
      az: "Qana",
      ru: "Гана",
      de: "Ghana",
      fr: "Ghana",
      fa: "غنا",
      ar: "غانا",
      tk: "Gana",
      kk: "Гана",
      ky: "Гана",
      zh: "加纳",
      bg: "Гана",
      ur: "گھانا",
      uz: "Gana",
      sw: "Ghana",
      so: "Gaana",
      id: "Ghana",
    },
  },
  {
    code: "CI",
    slug: "ivory-coast",
    flag: "🇨🇮",
    name: {
      en: "Ivory Coast",
      tr: "Fildişi Sahili",
      az: "Kotd’ivuar",
      ru: "Кот-д’Ивуар",
      de: "Elfenbeinküste",
      fr: "Côte d’Ivoire",
      fa: "ساحل عاج",
      ar: "ساحل العاج",
      tk: "Kot-d’Iwuar",
      kk: "Кот-д’Ивуар",
      ky: "Кот-д’Ивуар",
      zh: "科特迪瓦",
      bg: "Кот д’Ивоар",
      ur: "آئیوری کوسٹ",
      uz: "Kot-d’Ivuar",
      sw: "Côte d’Ivoire",
      so: "Xeebta Foolmaroodi",
      id: "Pantai Gading",
    },
  },
  {
    code: "SN",
    slug: "senegal",
    flag: "🇸🇳",
    name: {
      en: "Senegal",
      tr: "Senegal",
      az: "Seneqal",
      ru: "Сенегал",
      de: "Senegal",
      fr: "Sénégal",
      fa: "سنگال",
      ar: "السنغال",
      tk: "Senegal",
      kk: "Сенегал",
      ky: "Сенегал",
      zh: "塞内加尔",
      bg: "Сенегал",
      ur: "سینیگال",
      uz: "Senegal",
      sw: "Senegal",
      so: "Sinigaal",
      id: "Senegal",
    },
  },
  {
    code: "CM",
    slug: "cameroon",
    flag: "🇨🇲",
    name: {
      en: "Cameroon",
      tr: "Kamerun",
      az: "Kamerun",
      ru: "Камерун",
      de: "Kamerun",
      fr: "Cameroun",
      fa: "کامرون",
      ar: "الكاميرون",
      tk: "Kamerun",
      kk: "Камерун",
      ky: "Камерун",
      zh: "喀麦隆",
      bg: "Камерун",
      ur: "کیمرون",
      uz: "Kamerun",
      sw: "Kameruni",
      so: "Kameruun",
      id: "Kamerun",
    },
  },
  {
    code: "ZA",
    slug: "south-africa",
    flag: "🇿🇦",
    name: {
      en: "South Africa",
      tr: "Güney Afrika",
      az: "Cənubi Afrika",
      ru: "ЮАР",
      de: "Südafrika",
      fr: "Afrique du Sud",
      fa: "آفریقای جنوبی",
      ar: "جنوب أفريقيا",
      tk: "Günorta Afrika",
      kk: "Оңтүстік Африка",
      ky: "Түштүк Африка",
      zh: "南非",
      bg: "Южна Африка",
      ur: "جنوبی افریقہ",
      uz: "Janubiy Afrika",
      sw: "Afrika Kusini",
      so: "Koonfur Afrika",
      id: "Afrika Selatan",
    },
  },
  {
    code: "RW",
    slug: "rwanda",
    flag: "🇷🇼",
    name: {
      en: "Rwanda",
      tr: "Ruanda",
      az: "Ruanda",
      ru: "Руанда",
      de: "Ruanda",
      fr: "Rwanda",
      fa: "رواندا",
      ar: "رواندا",
      tk: "Ruanda",
      kk: "Руанда",
      ky: "Руанда",
      zh: "卢旺达",
      bg: "Руанда",
      ur: "روانڈا",
      uz: "Ruanda",
      sw: "Rwanda",
      so: "Ruwanda",
      id: "Rwanda",
    },
  },
  {
    code: "MZ",
    slug: "mozambique",
    flag: "🇲🇿",
    name: {
      en: "Mozambique",
      tr: "Mozambik",
      az: "Mozambik",
      ru: "Мозамбик",
      de: "Mosambik",
      fr: "Mozambique",
      fa: "موزامبیک",
      ar: "موزمبيق",
      tk: "Mozambik",
      kk: "Мозамбик",
      ky: "Мозамбик",
      zh: "莫桑比克",
      bg: "Мозамбик",
      ur: "موزمبیق",
      uz: "Mozambik",
      sw: "Msumbiji",
      so: "Musambiig",
      id: "Mozambik",
    },
  },
  {
    code: "AO",
    slug: "angola",
    flag: "🇦🇴",
    name: {
      en: "Angola",
      tr: "Angola",
      az: "Anqola",
      ru: "Ангола",
      de: "Angola",
      fr: "Angola",
      fa: "آنگولا",
      ar: "أنغولا",
      tk: "Angola",
      kk: "Ангола",
      ky: "Ангола",
      zh: "安哥拉",
      bg: "Ангола",
      ur: "انگولا",
      uz: "Angola",
      sw: "Angola",
      so: "Angoola",
      id: "Angola",
    },
  },
  {
    code: "SO",
    slug: "somalia",
    flag: "🇸🇴",
    name: {
      en: "Somalia",
      tr: "Somali",
      az: "Somali",
      ru: "Сомали",
      de: "Somalia",
      fr: "Somalie",
      fa: "سومالی",
      ar: "الصومال",
      tk: "Somali",
      kk: "Сомали",
      ky: "Сомали",
      zh: "索马里",
      bg: "Сомалия",
      ur: "صومالیہ",
      uz: "Somali",
      sw: "Somalia",
      so: "Soomaaliya",
      id: "Somalia",
    },
  },
  {
    code: "CD",
    slug: "dr-congo",
    flag: "🇨🇩",
    name: {
      en: "DR Congo",
      tr: "Kongo DC",
      az: "KDR Konqo",
      ru: "ДР Конго",
      de: "DR Kongo",
      fr: "RD Congo",
      fa: "جمهوری دموکراتیک کنگو",
      ar: "جمهورية الكونغو الديمقراطية",
      tk: "DR Kongo",
      kk: "ДР Конго",
      ky: "ДР Конго",
      zh: "刚果民主共和国",
      bg: "ДР Конго",
      ur: "ڈی آر کانگو",
      uz: "DR Kongo",
      sw: "DR Congo",
      so: "Jamhuuriyadda Kongo",
      id: "DR Kongo",
    },
  },
  {
    code: "MG",
    slug: "madagascar",
    flag: "🇲🇬",
    name: {
      en: "Madagascar",
      tr: "Madagaskar",
      az: "Madaqaskar",
      ru: "Мадагаскар",
      de: "Madagaskar",
      fr: "Madagascar",
      fa: "ماداگاسکار",
      ar: "مدغشقر",
      tk: "Madagaskar",
      kk: "Мадагаскар",
      ky: "Мадагаскар",
      zh: "马达加斯加",
      bg: "Мадагаскар",
      ur: "مڈغاسکر",
      uz: "Madagaskar",
      sw: "Madagaska",
      so: "Madagaskar",
      id: "Madagaskar",
    },
  },
  {
    code: "ZM",
    slug: "zambia",
    flag: "🇿🇲",
    name: {
      en: "Zambia",
      tr: "Zambiya",
      az: "Zambiya",
      ru: "Замбия",
      de: "Sambia",
      fr: "Zambie",
      fa: "زامبیا",
      ar: "زامبيا",
      tk: "Zambiýa",
      kk: "Замбия",
      ky: "Замбия",
      zh: "赞比亚",
      bg: "Замбия",
      ur: "زامبیا",
      uz: "Zambiya",
      sw: "Zambia",
      so: "Sambiya",
      id: "Zambia",
    },
  },
  {
    code: "ZW",
    slug: "zimbabwe",
    flag: "🇿🇼",
    name: {
      en: "Zimbabwe",
      tr: "Zimbabve",
      az: "Zimbabve",
      ru: "Зимбабве",
      de: "Simbabwe",
      fr: "Zimbabwe",
      fa: "زیمبابوه",
      ar: "زيمبابوي",
      tk: "Zimbabwe",
      kk: "Зимбабве",
      ky: "Зимбабве",
      zh: "津巴布韦",
      bg: "Зимбабве",
      ur: "زمبابوے",
      uz: "Zimbabve",
      sw: "Zimbabwe",
      so: "Simbaabwe",
      id: "Zimbabwe",
    },
  },
  {
    code: "NA",
    slug: "namibia",
    flag: "🇳🇦",
    name: {
      en: "Namibia",
      tr: "Namibya",
      az: "Namibiya",
      ru: "Намибия",
      de: "Namibia",
      fr: "Namibie",
      fa: "نامیبیا",
      ar: "ناميبيا",
      tk: "Namibiýa",
      kk: "Намибия",
      ky: "Намибия",
      zh: "纳米比亚",
      bg: "Намибия",
      ur: "نمیبیا",
      uz: "Namibiya",
      sw: "Namibia",
      so: "Namiibiya",
      id: "Namibia",
    },
  },
  {
    code: "BW",
    slug: "botswana",
    flag: "🇧🇼",
    name: {
      en: "Botswana",
      tr: "Botsvana",
      az: "Botsvana",
      ru: "Ботсвана",
      de: "Botswana",
      fr: "Botswana",
      fa: "بوتسوانا",
      ar: "بوتسوانا",
      tk: "Botswana",
      kk: "Ботсвана",
      ky: "Ботсвана",
      zh: "博茨瓦纳",
      bg: "Ботсвана",
      ur: "بوٹسوانا",
      uz: "Botswana",
      sw: "Botswana",
      so: "Botswana",
      id: "Botswana",
    },
  },
  {
    code: "GM",
    slug: "gambia",
    flag: "🇬🇲",
    name: {
      en: "Gambia",
      tr: "Gambiya",
      az: "Qambiya",
      ru: "Гамбия",
      de: "Gambia",
      fr: "Gambie",
      fa: "گامبیا",
      ar: "غامبيا",
      tk: "Gambiýa",
      kk: "Гамбия",
      ky: "Гамбия",
      zh: "冈比亚",
      bg: "Гамбия",
      ur: "گیمبیا",
      uz: "Gambiya",
      sw: "Gambia",
      so: "Gambiya",
      id: "Gambia",
    },
  },
  {
    code: "GN",
    slug: "guinea",
    flag: "🇬🇳",
    name: {
      en: "Guinea",
      tr: "Gine",
      az: "Qvineya",
      ru: "Гвинея",
      de: "Guinea",
      fr: "Guinée",
      fa: "گینه",
      ar: "غينيا",
      tk: "Gwineýa",
      kk: "Гвинея",
      ky: "Гвинея",
      zh: "几内亚",
      bg: "Гвинея",
      ur: "گنی",
      uz: "Gvineya",
      sw: "Gine",
      so: "Gini",
      id: "Guinea",
    },
  },
  {
    code: "ML",
    slug: "mali",
    flag: "🇲🇱",
    name: {
      en: "Mali",
      tr: "Mali",
      az: "Mali",
      ru: "Мали",
      de: "Mali",
      fr: "Mali",
      fa: "مالی",
      ar: "مالي",
      tk: "Mali",
      kk: "Мали",
      ky: "Мали",
      zh: "马里",
      bg: "Мали",
      ur: "مالی",
      uz: "Mali",
      sw: "Mali",
      so: "Maali",
      id: "Mali",
    },
  },
  {
    code: "BF",
    slug: "burkina-faso",
    flag: "🇧🇫",
    name: {
      en: "Burkina Faso",
      tr: "Burkina Faso",
      az: "Burkina Faso",
      ru: "Буркина-Фасо",
      de: "Burkina Faso",
      fr: "Burkina Faso",
      fa: "بورکینافاسو",
      ar: "بوركينا فاسو",
      tk: "Burkina-Faso",
      kk: "Буркина-Фасо",
      ky: "Буркина-Фасо",
      zh: "布基纳法索",
      bg: "Буркина Фасо",
      ur: "برکینا فاسو",
      uz: "Burkina-Faso",
      sw: "Burkina Faso",
      so: "Burkiina Faaso",
      id: "Burkina Faso",
    },
  },
  {
    code: "BJ",
    slug: "benin",
    flag: "🇧🇯",
    name: {
      en: "Benin",
      tr: "Benin",
      az: "Benin",
      ru: "Бенин",
      de: "Benin",
      fr: "Bénin",
      fa: "بنین",
      ar: "بنين",
      tk: "Benin",
      kk: "Бенин",
      ky: "Бенин",
      zh: "贝宁",
      bg: "Бенин",
      ur: "بینن",
      uz: "Benin",
      sw: "Benin",
      so: "Biniin",
      id: "Benin",
    },
  },
  {
    code: "TG",
    slug: "togo",
    flag: "🇹🇬",
    name: {
      en: "Togo",
      tr: "Togo",
      az: "Toqo",
      ru: "Того",
      de: "Togo",
      fr: "Togo",
      fa: "توگو",
      ar: "توغو",
      tk: "Togo",
      kk: "Того",
      ky: "Того",
      zh: "多哥",
      bg: "Того",
      ur: "ٹوگو",
      uz: "Togo",
      sw: "Togo",
      so: "Toogo",
      id: "Togo",
    },
  },
  {
    code: "MR",
    slug: "mauritania",
    flag: "🇲🇷",
    name: {
      en: "Mauritania",
      tr: "Moritanya",
      az: "Mavritaniya",
      ru: "Мавритания",
      de: "Mauretanien",
      fr: "Mauritanie",
      fa: "موریتانی",
      ar: "موريتانيا",
      tk: "Mawritaniýa",
      kk: "Мавритания",
      ky: "Мавритания",
      zh: "毛里塔尼亚",
      bg: "Мавритания",
      ur: "موریتانیہ",
      uz: "Mavritaniya",
      sw: "Mauritania",
      so: "Mawritaaniya",
      id: "Mauritania",
    },
  },
  {
    code: "ER",
    slug: "eritrea",
    flag: "🇪🇷",
    name: {
      en: "Eritrea",
      tr: "Eritre",
      az: "Eritreya",
      ru: "Эритрея",
      de: "Eritrea",
      fr: "Érythrée",
      fa: "اریتره",
      ar: "إريتريا",
      tk: "Eritreýa",
      kk: "Эритрея",
      ky: "Эритрея",
      zh: "厄立特里亚",
      bg: "Еритрея",
      ur: "اریٹیریا",
      uz: "Eritreya",
      sw: "Eritrea",
      so: "Eritereya",
      id: "Eritrea",
    },
  },

  // === Oceania ===
  {
    code: "AU",
    slug: "australia",
    flag: "🇦🇺",
    name: {
      en: "Australia",
      tr: "Avustralya",
      az: "Avstraliya",
      ru: "Австралия",
      de: "Australien",
      fr: "Australie",
      fa: "استرالیا",
      ar: "أستراليا",
      tk: "Awstraliýa",
      kk: "Австралия",
      ky: "Австралия",
      zh: "澳大利亚",
      bg: "Австралия",
      ur: "آسٹریلیا",
      uz: "Avstraliya",
      sw: "Australia",
      so: "Awstaraaliya",
      id: "Australia",
    },
  },
  {
    code: "NZ",
    slug: "new-zealand",
    flag: "🇳🇿",
    name: {
      en: "New Zealand",
      tr: "Yeni Zelanda",
      az: "Yeni Zelandiya",
      ru: "Новая Зеландия",
      de: "Neuseeland",
      fr: "Nouvelle-Zélande",
      fa: "نیوزیلند",
      ar: "نيوزيلندا",
      tk: "Täze Zelandiýa",
      kk: "Жаңа Зеландия",
      ky: "Жаңы Зеландия",
      zh: "新西兰",
      bg: "Нова Зеландия",
      ur: "نیوزی لینڈ",
      uz: "Yangi Zelandiya",
      sw: "Nyuzilandi",
      so: "Niyuu Siilaand",
      id: "Selandia Baru",
    },
  },
  {
    code: "FJ",
    slug: "fiji",
    flag: "🇫🇯",
    name: {
      en: "Fiji",
      tr: "Fiji",
      az: "Fici",
      ru: "Фиджи",
      de: "Fidschi",
      fr: "Fidji",
      fa: "فیجی",
      ar: "فيجي",
      tk: "Fiji",
      kk: "Фиджи",
      ky: "Фиджи",
      zh: "斐济",
      bg: "Фиджи",
      ur: "فجی",
      uz: "Fiji",
      sw: "Fiji",
      so: "Fiji",
      id: "Fiji",
    },
  },
];
