import type { Program, ProgramCategory } from '@/types';

export const seedCategories: ProgramCategory[] = [
  {
    slug: 'medicine',
    name: { en: 'Medicine', tr: 'Tıp', az: 'Tibb', ru: 'Медицина', de: 'Medizin', fr: 'Médecine', fa: 'پزشکی', ar: 'الطب', tk: 'Medisina', kk: 'Медицина', ky: 'Медицина', zh: '医学', bg: 'Медицина', ur: 'طب', uz: 'Tibbiyot', sw: 'Tiba', so: 'Caafimaadka', id: 'Kedokteran' },
    icon: 'stethoscope',
  },
  {
    slug: 'engineering',
    name: { en: 'Engineering', tr: 'Mühendislik', az: 'Mühəndislik', ru: 'Инженерия', de: 'Ingenieurwesen', fr: 'Ingénierie', fa: 'مهندسی', ar: 'الهندسة', tk: 'Inženerlik', kk: 'Инженерия', ky: 'Инженерия', zh: '工程学', bg: 'Инженерство', ur: 'انجینئرنگ', uz: 'Muhandislik', sw: 'Uhandisi', so: 'Injineeriyada', id: 'Teknik' },
    icon: 'cog',
  },
  {
    slug: 'computer-science',
    name: { en: 'Computer Science', tr: 'Bilgisayar Bilimleri', az: 'Kompüter Elmləri', ru: 'Компьютерные науки', de: 'Informatik', fr: 'Informatique', fa: 'علوم کامپیوتر', ar: 'علوم الحاسوب', tk: 'Kompýuter ylymlary', kk: 'Компьютерлік ғылымдар', ky: 'Компьютер илимдери', zh: '计算机科学', bg: 'Компютърни науки', ur: 'کمپیوٹر سائنس', uz: 'Kompyuter fanlari', sw: 'Sayansi ya Kompyuta', so: 'Sayniska Kombiyuutarka', id: 'Ilmu Komputer' },
    icon: 'code',
  },
  {
    slug: 'business',
    name: { en: 'Business', tr: 'İşletme', az: 'Biznes', ru: 'Бизнес', de: 'Wirtschaft', fr: 'Commerce', fa: 'کسب و کار', ar: 'إدارة الأعمال', tk: 'Biznes', kk: 'Бизнес', ky: 'Бизнес', zh: '商学', bg: 'Бизнес', ur: 'بزنس', uz: 'Biznes', sw: 'Biashara', so: 'Ganacsiga', id: 'Bisnis' },
    icon: 'briefcase',
  },
  {
    slug: 'law',
    name: { en: 'Law', tr: 'Hukuk', az: 'Hüquq', ru: 'Право', de: 'Jura', fr: 'Droit', fa: 'حقوق', ar: 'القانون', tk: 'Hukuk', kk: 'Құқық', ky: 'Укук', zh: '法学', bg: 'Право', ur: 'قانون', uz: 'Huquq', sw: 'Sheria', so: 'Sharciga', id: 'Hukum' },
    icon: 'scale',
  },
  {
    slug: 'architecture',
    name: { en: 'Architecture', tr: 'Mimarlık', az: 'Memarlıq', ru: 'Архитектура', de: 'Architektur', fr: 'Architecture', fa: 'معماری', ar: 'العمارة', tk: 'Arhitektura', kk: 'Сәулет', ky: 'Архитектура', zh: '建筑学', bg: 'Архитектура', ur: 'فن تعمیر', uz: 'Arxitektura', sw: 'Usanifu', so: 'Naqshada', id: 'Arsitektur' },
    icon: 'compass',
  },
  {
    slug: 'dentistry',
    name: { en: 'Dentistry', tr: 'Diş Hekimliği', az: 'Stomatologiya', ru: 'Стоматология', de: 'Zahnmedizin', fr: 'Odontologie', fa: 'دندانپزشکی', ar: 'طب الأسنان', tk: 'Diş lukmançylygy', kk: 'Стоматология', ky: 'Стоматология', zh: '牙科', bg: 'Стоматология', ur: 'دندان سازی', uz: 'Stomatologiya', sw: 'Menzi wa meno', so: 'Ilgaxa ilkaha', id: 'Kedokteran Gigi' },
    icon: 'smile',
  },
  {
    slug: 'arts',
    name: { en: 'Arts & Design', tr: 'Sanat ve Tasarım', az: 'İncəsənət və Dizayn', ru: 'Искусство и дизайн', de: 'Kunst & Design', fr: 'Arts & Design', fa: 'هنر و طراحی', ar: 'الفنون والتصميم', tk: 'Sungat we dizaýn', kk: 'Өнер және дизайн', ky: 'Искусство жана дизайн', zh: '艺术与设计', bg: 'Изкуства и дизайн', ur: 'آرٹ اور ڈیزائن', uz: "San'at va dizayn", sw: 'Sanaa na Ubunifu', so: 'Fanka iyo Naqshadaynta', id: 'Seni dan Desain' },
    icon: 'palette',
  },
  {
    slug: 'social-sciences',
    name: { en: 'Social Sciences', tr: 'Sosyal Bilimler', az: 'Sosial Elmlər', ru: 'Социальные науки', de: 'Sozialwissenschaften', fr: 'Sciences sociales', fa: 'علوم اجتماعی', ar: 'العلوم الاجتماعية', tk: 'Jemgyýetçilik ylymlary', kk: 'Әлеуметтік ғылымдар', ky: 'Социалдык илимдер', zh: '社会科学', bg: 'Социални науки', ur: 'سماجی علوم', uz: 'Ijtimoiy fanlar', sw: 'Sayansi za Jamii', so: 'Cilimada Bulshada', id: 'Ilmu Sosial' },
    icon: 'users',
  },
  {
    slug: 'health-sciences',
    name: { en: 'Health Sciences', tr: 'Sağlık Bilimleri', az: 'Səhiyyə Elmləri', ru: 'Медицинские науки', de: 'Gesundheitswissenschaften', fr: 'Sciences de la santé', fa: 'علوم بهداشت', ar: 'العلوم الصحية', tk: 'Saglyk ylymlary', kk: 'Денсаулық ғылымдары', ky: 'Саламаттык илимдери', zh: '健康科学', bg: 'Здравни науки', ur: 'صحت علوم', uz: "Sog'liqni saqlash fanlari", sw: 'Sayansi za Afya', so: 'Cilimada Caafimaadka', id: 'Ilmu Kesehatan' },
    icon: 'heart-pulse',
  },
  {
    slug: 'natural-sciences',
    name: { en: 'Natural Sciences', tr: 'Fen Bilimleri', az: 'Təbiət Elmləri', ru: 'Естественные науки', de: 'Naturwissenschaften', fr: 'Sciences naturelles', fa: 'علوم طبیعی', ar: 'العلوم الطبيعية', tk: 'Tebigy ylymlar', kk: 'Жаратылыстану ғылымдары', ky: 'Жаратылыш илимдери', zh: '自然科学', bg: 'Естествени науки', ur: 'قدرتی علوم', uz: 'Tabiiy fanlar', sw: 'Sayansi za Asili', so: 'Cilimada Dabiiciga', id: 'Ilmu Alam' },
    icon: 'atom',
  },
  {
    slug: 'humanities',
    name: { en: 'Humanities', tr: 'Beşeri Bilimler', az: 'Humanitar Elmlər', ru: 'Гуманитарные науки', de: 'Geisteswissenschaften', fr: 'Lettres et sciences humaines', fa: 'علوم انسانی', ar: 'العلوم الإنسانية', tk: 'Gumanitar ylymlar', kk: 'Гуманитарлық ғылымдар', ky: 'Гуманитардык илимдер', zh: '人文学科', bg: 'Хуманитарни науки', ur: 'ہیومینٹیز', uz: 'Gumanitar fanlar', sw: 'Sayansi za Binadamu', so: 'Cilimada Aadanaha', id: 'Humaniora' },
    icon: 'book-open',
  },
  {
    slug: 'communication',
    name: { en: 'Communication', tr: 'İletişim', az: 'Kommunikasiya', ru: 'Коммуникации', de: 'Kommunikation', fr: 'Communication', fa: 'ارتباطات', ar: 'الاتصال', tk: 'Aragatnaşyk', kk: 'Коммуникация', ky: 'Коммуникация', zh: '传播学', bg: 'Комуникации', ur: 'ذرائع ابلاغ', uz: 'Kommunikatsiya', sw: 'Mawasiliano', so: 'Isgaarsiinta', id: 'Komunikasi' },
    icon: 'radio',
  },
  {
    slug: 'tourism',
    name: { en: 'Tourism & Hospitality', tr: 'Turizm ve Otel İşletmeciliği', az: 'Turizm və Qonaqpərvərlik', ru: 'Туризм и гостеприимство', de: 'Tourismus & Gastgewerbe', fr: 'Tourisme & Hôtellerie', fa: 'گردشگری و مهمانداری', ar: 'السياحة والضيافة', tk: 'Syýahatçylyk we myhmançylyk', kk: 'Туризм және қонақжайлылық', ky: 'Туризм жана меймандостук', zh: '旅游与酒店管理', bg: 'Туризъм и хотелиерство', ur: 'سیاحت اور مہمان نوازی', uz: "Turizm va mehmondo'stlik", sw: 'Utalii na Ukarimu', so: 'Dalooska iyo Martigelinta', id: 'Pariwisata dan Perhotelan' },
    icon: 'map-pin',
  },
  {
    slug: 'agriculture',
    name: { en: 'Agriculture & Food', tr: 'Tarım ve Gıda', az: 'Kənd Təsərrüfatı və Qida', ru: 'Сельское хозяйство и питание', de: 'Landwirtschaft & Ernährung', fr: 'Agriculture & Agroalimentaire', fa: 'کشاورزی و غذا', ar: 'الزراعة والغذاء', tk: 'Oba hojalygy we iýmit', kk: 'Ауыл шаруашылығы және азық-түлік', ky: 'Айыл чарба жана азык-түлүк', zh: '农业与食品', bg: 'Селско стопанство и храни', ur: 'زراعت اور خوراک', uz: "Qishloq xo'jaligi va oziq-ovqat", sw: 'Kilimo na Chakula', so: 'Beeraha iyo Cuntada', id: 'Pertanian dan Pangan' },
    icon: 'leaf',
  },
];

export const seedPrograms: Program[] = [
  {
    id: 'p-med-bach',
    slug: 'medicine',
    name: { en: 'Medicine (MD)', tr: 'Tıp', az: 'Tibb', ru: 'Медицина', de: 'Medizin (Dr. med.)', fr: 'Médecine (MD)', fa: 'پزشکی (MD)', ar: 'الطب (دكتوراه)', tk: 'Medisina (MD)', kk: 'Медицина (MD)', ky: 'Медицина (MD)', zh: '医学 (MD)', bg: 'Медицина (MD)', ur: 'طب (MD)', uz: 'Tibbiyot (MD)', sw: 'Tiba (MD)', so: 'Caafimaadka (MD)', id: 'Kedokteran (MD)' },
    degreeLevel: 'bachelor',
    categorySlug: 'medicine',
    durationYears: 6,
  },
  {
    id: 'p-med-master',
    slug: 'medicine-master',
    name: { en: 'Medical Specialization', tr: 'Tıp Uzmanlığı', az: 'Tibb İxtisası', ru: 'Медицинская специализация', de: 'Medizinische Spezialisierung', fr: 'Spécialisation médicale', fa: 'تخصص پزشکی', ar: 'التخصص الطبي', tk: 'Lukmançylyk hünärmenligi', kk: 'Медициналық мамандану', ky: 'Медициналык адистешүү', zh: '医学专科', bg: 'Медицинска специализация', ur: 'طبی خصوصی', uz: 'Tibbiy ixtisoslashuv', sw: 'Utaalamu wa Tiba', so: 'Takhasuska Caafimaadka', id: 'Spesialisasi Kedokteran' },
    degreeLevel: 'master',
    categorySlug: 'medicine',
    durationYears: 5,
  },
  {
    id: 'p-dent-bach',
    slug: 'dentistry',
    name: { en: 'Dentistry', tr: 'Diş Hekimliği', az: 'Stomatologiya', ru: 'Стоматология', de: 'Zahnmedizin', fr: 'Odontologie', fa: 'دندانپزشکی', ar: 'طب الأسنان', tk: 'Diş lukmançylygy', kk: 'Стоматология', ky: 'Стоматология', zh: '牙科', bg: 'Стоматология', ur: 'دندان سازی', uz: 'Stomatologiya', sw: 'Menzi wa meno', so: 'Ilgaxa ilkaha', id: 'Kedokteran Gigi' },
    degreeLevel: 'bachelor',
    categorySlug: 'dentistry',
    durationYears: 5,
  },
  {
    id: 'p-cs-bach',
    slug: 'computer-engineering',
    name: { en: 'Computer Engineering', tr: 'Bilgisayar Mühendisliği', az: 'Kompüter Mühəndisliyi', ru: 'Компьютерная инженерия', de: 'Computertechnik', fr: 'Génie informatique', fa: 'مهندسی کامپیوتر', ar: 'هندسة الحاسوب', tk: 'Kompýuter inženerligi', kk: 'Компьютерлік инженерия', ky: 'Компьютер инженериясы', zh: '计算机工程', bg: 'Компютърно инженерство', ur: 'کمپیوٹر انجینئرنگ', uz: 'Kompyuter muhandisligi', sw: 'Uhandisi wa Kompyuta', so: 'Injineeriyada Kombiyuutarka', id: 'Teknik Komputer' },
    degreeLevel: 'bachelor',
    categorySlug: 'computer-science',
    durationYears: 4,
  },
  {
    id: 'p-cs-master',
    slug: 'computer-science-master',
    name: { en: 'Computer Science (MSc)', tr: 'Bilgisayar Bilimleri (YL)', az: 'Kompüter Elmləri (Magistr)', ru: 'Компьютерные науки (Магистр)', de: 'Informatik (MSc)', fr: 'Informatique (MSc)', fa: 'علوم کامپیوتر (کارشناسی ارشد)', ar: 'علوم الحاسوب (ماجستير)', tk: 'Kompýuter ylymlary (magistr)', kk: 'Компьютерлік ғылымдар (магистр)', ky: 'Компьютер илимдери (магистр)', zh: '计算机科学（硕士）', bg: 'Компютърни науки (магистър)', ur: 'کمپیوٹر سائنس (ماسٹر)', uz: 'Kompyuter fanlari (magistr)', sw: 'Sayansi ya Kompyuta (MSc)', so: 'Sayniska Kombiyuutarka (MSc)', id: 'Ilmu Komputer (MSc)' },
    degreeLevel: 'master',
    categorySlug: 'computer-science',
    durationYears: 2,
  },
  {
    id: 'p-se-bach',
    slug: 'software-engineering',
    name: { en: 'Software Engineering', tr: 'Yazılım Mühendisliği', az: 'Proqram Təminatı Mühəndisliyi', ru: 'Программная инженерия', de: 'Softwaretechnik', fr: 'Génie logiciel', fa: 'مهندسی نرمافزار', ar: 'هندسة البرمجيات', tk: 'Programma inženerligi', kk: 'Бағдарламалық қамтамасыз ету инженериясы', ky: 'Программалык камсыздоо инженериясы', zh: '软件工程', bg: 'Софтуерно инженерство', ur: 'سافٹ ویئر انجینئرنگ', uz: 'Dasturiy ta’minot muhandisligi', sw: 'Uhandisi wa Programu', so: 'Injineeriyada Software-ka', id: 'Rekayasa Perangkat Lunak' },
    degreeLevel: 'bachelor',
    categorySlug: 'computer-science',
    durationYears: 4,
  },
  {
    id: 'p-eng-mech',
    slug: 'mechanical-engineering',
    name: { en: 'Mechanical Engineering', tr: 'Makine Mühendisliği', az: 'Mexanika Mühəndisliyi', ru: 'Машиностроение', de: 'Maschinenbau', fr: 'Génie mécanique', fa: 'مهندسی مکانیک', ar: 'الهندسة الميكانيكية', tk: 'Mehaniki inženerlik', kk: 'Машина жасау инженериясы', ky: 'Механикалык инженерия', zh: '机械工程', bg: 'Машинно инженерство', ur: 'مکینیکل انجینئرنگ', uz: 'Mashinasozlik muhandisligi', sw: 'Uhandisi wa Mitambo', so: 'Injineeriyada Makaanikada', id: 'Teknik Mesin' },
    degreeLevel: 'bachelor',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-eng-elec',
    slug: 'electrical-engineering',
    name: { en: 'Electrical Engineering', tr: 'Elektrik Mühendisliği', az: 'Elektrik Mühəndisliyi', ru: 'Электротехника', de: 'Elektrotechnik', fr: 'Génie électrique', fa: 'مهندسی برق', ar: 'الهندسة الكهربائية', tk: 'Elektrik inženerligi', kk: 'Электр инженериясы', ky: 'Электр инженериясы', zh: '电气工程', bg: 'Електроинженерство', ur: 'الیکٹریکل انجینئرنگ', uz: 'Elektr muhandisligi', sw: 'Uhandisi wa Umeme', so: 'Injineeriyada Korontada', id: 'Teknik Elektro' },
    degreeLevel: 'bachelor',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-eng-civil',
    slug: 'civil-engineering',
    name: { en: 'Civil Engineering', tr: 'İnşaat Mühendisliği', az: 'İnşaat Mühəndisliyi', ru: 'Гражданское строительство', de: 'Bauingenieurwesen', fr: 'Génie civil', fa: 'مهندسی عمران', ar: 'الهندسة المدنية', tk: 'Gurluşyk inženerligi', kk: 'Құрылыс инженериясы', ky: 'Курулуш инженериясы', zh: '土木工程', bg: 'Строително инженерство', ur: 'سول انجینئرنگ', uz: 'Qurilish muhandisligi', sw: 'Uhandisi wa Ujenzi', so: 'Injineeriyada Dhismaha', id: 'Teknik Sipil' },
    degreeLevel: 'bachelor',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-bus-bach',
    slug: 'business-administration',
    name: { en: 'Business Administration', tr: 'İşletme', az: 'Biznesin İdarəedilməsi', ru: 'Бизнес-администрирование', de: 'Betriebswirtschaftslehre', fr: 'Administration des affaires', fa: 'مدیریت بازرگانی', ar: 'إدارة الأعمال', tk: 'Biznes dolandyryşy', kk: 'Іскерлік әкімшілендіру', ky: 'Бизнес башкаруу', zh: '工商管理', bg: 'Бизнес администрация', ur: 'بزنس ایڈمنسٹریشن', uz: 'Biznes boshqaruvi', sw: 'Usimamizi wa Biashara', so: 'Maamulka Ganacsiga', id: 'Administrasi Bisnis' },
    degreeLevel: 'bachelor',
    categorySlug: 'business',
    durationYears: 4,
  },
  {
    id: 'p-bus-mba',
    slug: 'mba',
    name: { en: 'MBA', tr: 'MBA', az: 'MBA', ru: 'MBA', de: 'MBA', fr: 'MBA', fa: 'MBA', ar: 'ماجستير إدارة الأعمال', tk: 'MBA', kk: 'MBA', ky: 'MBA', zh: '工商管理硕士', bg: 'MBA', ur: 'MBA', uz: 'MBA', sw: 'MBA', so: 'MBA', id: 'MBA' },
    degreeLevel: 'master',
    categorySlug: 'business',
    durationYears: 2,
  },
  {
    id: 'p-bus-irm',
    slug: 'international-relations',
    name: { en: 'International Relations', tr: 'Uluslararası İlişkiler', az: 'Beynəlxalq Münasibətlər', ru: 'Международные отношения', de: 'Internationale Beziehungen', fr: 'Relations internationales', fa: 'روابط بینالملل', ar: 'العلاقات الدولية', tk: 'Halkara gatnaşyklar', kk: 'Халықаралық қатынастар', ky: 'Эл аралык мамилелер', zh: '国际关系', bg: 'Международни отношения', ur: 'بین الاقوامی تعلقات', uz: 'Xalqaro munosabatlar', sw: 'Mahusiano ya Kimataifa', so: 'Xiriirka Caalamiga', id: 'Hubungan Internasional' },
    degreeLevel: 'bachelor',
    categorySlug: 'business',
    durationYears: 4,
  },
  {
    id: 'p-law-bach',
    slug: 'law',
    name: { en: 'Law', tr: 'Hukuk', az: 'Hüquq', ru: 'Право', de: 'Jura', fr: 'Droit', fa: 'حقوق', ar: 'القانون', tk: 'Hukuk', kk: 'Құқық', ky: 'Укук', zh: '法学', bg: 'Право', ur: 'قانون', uz: 'Huquq', sw: 'Sheria', so: 'Sharciga', id: 'Hukum' },
    degreeLevel: 'bachelor',
    categorySlug: 'law',
    durationYears: 4,
  },
  {
    id: 'p-arch-bach',
    slug: 'architecture',
    name: { en: 'Architecture', tr: 'Mimarlık', az: 'Memarlıq', ru: 'Архитектура', de: 'Architektur', fr: 'Architecture', fa: 'معماری', ar: 'العمارة', tk: 'Arhitektura', kk: 'Сәулет', ky: 'Архитектура', zh: '建筑学', bg: 'Архитектура', ur: 'فن تعمیر', uz: 'Arxitektura', sw: 'Usanifu', so: 'Naqshada', id: 'Arsitektur' },
    degreeLevel: 'bachelor',
    categorySlug: 'architecture',
    durationYears: 4,
  },
  {
    id: 'p-arts-bach',
    slug: 'industrial-design',
    name: { en: 'Industrial Design', tr: 'Endüstriyel Tasarım', az: 'Sənaye Dizaynı', ru: 'Промышленный дизайн', de: 'Industriedesign', fr: 'Design industriel', fa: 'طراحی صنعتی', ar: 'التصميم الصناعي', tk: 'Senagat dizaýny', kk: 'Өнеркәсіптік дизайн', ky: 'Өнөр жай дизайн', zh: '工业设计', bg: 'Индустриален дизайн', ur: 'صنعتی ڈیزائن', uz: 'Sanoat dizayni', sw: 'Ubunifu wa Viwanda', so: 'Naqshadaynta Warshadaha', id: 'Desain Industri' },
    degreeLevel: 'bachelor',
    categorySlug: 'arts',
    durationYears: 4,
  },
  {
    id: 'p-ai-master',
    slug: 'artificial-intelligence',
    name: { en: 'Artificial Intelligence (MSc)', tr: 'Yapay Zeka (YL)', az: 'Süni İntellekt (Magistr)', ru: 'Искусственный интеллект (Магистр)', de: 'Künstliche Intelligenz (MSc)', fr: 'Intelligence artificielle (MSc)', fa: 'هوش مصنوعی (کارشناسی ارشد)', ar: 'الذكاء الاصطناعي (ماجستير)', tk: 'Emeli aň (magistr)', kk: 'Жасанды интеллект (магистр)', ky: 'Жасалма интеллект (магистр)', zh: '人工智能（硕士）', bg: 'Изкуствен интелект (магистър)', ur: 'مصنوعی ذہانت (ماسٹر)', uz: 'Sun’iy intellekt (magistr)', sw: 'Akili Bandia (MSc)', so: 'Sirdoonka Macmalka (MSc)', id: 'Kecerdasan Buatan (MSc)' },
    degreeLevel: 'master',
    categorySlug: 'computer-science',
    durationYears: 2,
  },
  {
    id: 'p-eng-mechatronics',
    slug: 'mechatronics-engineering',
    name: { en: 'Mechatronics Engineering', tr: 'Mekatronik Mühendisliği', az: 'Mekatronika Mühəndisliyi', ru: 'Мехатроника', de: 'Mechatronik', fr: 'Mécatronique', fa: 'مهندسی مکاترونیک', ar: 'هندسة الميكاترونكس', tk: 'Mehatronika inženerligi', kk: 'Мехатроника инженериясы', ky: 'Мехатроника инженериясы', zh: '机电一体化工程', bg: 'Мехатроника', ur: 'میکاٹرونکس انجینئرنگ', uz: 'Mexatronika muhandisligi', sw: 'Uhandisi wa Mekatroniki', so: 'Injineeriyada Mechatronics-ka', id: 'Teknik Mekatronika' },
    degreeLevel: 'bachelor',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-eng-chemical',
    slug: 'chemical-engineering',
    name: { en: 'Chemical Engineering', tr: 'Kimya Mühendisliği', az: 'Kimya Mühəndisliyi', ru: 'Химическая инженерия', de: 'Chemieingenieurwesen', fr: 'Génie chimique', fa: 'مهندسی شیمی', ar: 'الهندسة الكيميائية', tk: 'Himiýa inženerligi', kk: 'Химиялық инженерия', ky: 'Химиялык инженерия', zh: '化学工程', bg: 'Химично инженерство', ur: 'کیمیکل انجینئرنگ', uz: 'Kimyoviy muhandislik', sw: 'Uhandisi wa Kemia', so: 'Injineeriyada Kiimikada', id: 'Teknik Kimia' },
    degreeLevel: 'bachelor',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-eng-automotive',
    slug: 'automotive-engineering',
    name: { en: 'Automotive Engineering', tr: 'Otomotiv Mühendisliği', az: 'Avtomobil Mühəndisliyi', ru: 'Автомобильная инженерия', de: 'Fahrzeugtechnik', fr: 'Génie automobile', fa: 'مهندسی خودرو', ar: 'هندسة السيارات', tk: 'Awtomobil inženerligi', kk: 'Автомобиль инженериясы', ky: 'Автомобиль инженериясы', zh: '汽车工程', bg: 'Автомобилно инженерство', ur: 'آٹوموٹیو انجینئرنگ', uz: 'Avtomobil muhandisligi', sw: 'Uhandisi wa Magari', so: 'Injineeriyada Baabuurta', id: 'Teknik Otomotif' },
    degreeLevel: 'bachelor',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-eng-industrial',
    slug: 'industrial-engineering',
    name: { en: 'Industrial Engineering', tr: 'Endüstri Mühendisliği', az: 'Sənaye Mühəndisliyi', ru: 'Промышленная инженерия', de: 'Wirtschaftsingenieurwesen', fr: 'Génie industriel', fa: 'مهندسی صنایع', ar: 'الهندسة الصناعية', tk: 'Senagat inženerligi', kk: 'Өнеркәсіптік инженерия', ky: 'Өнөр жай инженериясы', zh: '工业工程', bg: 'Индустриално инженерство', ur: 'صنعتی انجینئرنگ', uz: 'Sanoat muhandisligi', sw: 'Uhandisi wa Viwanda', so: 'Injineeriyada Warshadaha', id: 'Teknik Industri' },
    degreeLevel: 'bachelor',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-eng-biomedical',
    slug: 'biomedical-engineering',
    name: { en: 'Biomedical Engineering', tr: 'Biyomedikal Mühendisliği', az: 'Biomedikal Mühəndisliyi', ru: 'Биомедицинская инженерия', de: 'Biomedizintechnik', fr: 'Génie biomédical', fa: 'مهندسی پزشکی', ar: 'الهندسة الطبية الحيوية', tk: 'Biomedisin inženerligi', kk: 'Биомедициналық инженерия', ky: 'Биомедициналык инженерия', zh: '生物医学工程', bg: 'Биомедицинско инженерство', ur: 'بایو میڈیکل انجینئرنگ', uz: 'Biomeditsina muhandisligi', sw: 'Uhandisi wa Biomedical', so: 'Injineeriyada Caafimaadka', id: 'Teknik Biomedis' },
    degreeLevel: 'bachelor',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-eng-aerospace',
    slug: 'aerospace-engineering',
    name: { en: 'Aerospace Engineering', tr: 'Havacılık ve Uzay Mühendisliği', az: 'Aviasiya və Kosmos Mühəndisliyi', ru: 'Аэрокосмическая инженерия', de: 'Luft- und Raumfahrttechnik', fr: 'Génie aérospatial', fa: 'مهندسی هوافضا', ar: 'هندسة الطيران والفضاء', tk: 'Awiasiýa we kosmos inženerligi', kk: 'Аэроғарыш инженериясы', ky: 'Аэрокосмостук инженерия', zh: '航空航天工程', bg: 'Аерокосмическо инженерство', ur: 'ایرو اسپیس انجینئرنگ', uz: 'Aviatsiya va kosmik muhandislik', sw: 'Uhandisi wa Anga', so: 'Injineeriyada Hawada', id: 'Teknik Dirgantara' },
    degreeLevel: 'bachelor',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-eng-energy',
    slug: 'energy-systems-engineering',
    name: { en: 'Energy Systems Engineering', tr: 'Enerji Sistemleri Mühendisliği', az: 'Enerji Sistemləri Mühəndisliyi', ru: 'Инженерия энергетических систем', de: 'Energiesystemtechnik', fr: 'Ingénierie des systèmes énergétiques', fa: 'مهندسی سیستمهای انرژی', ar: 'هندسة أنظمة الطاقة', tk: 'Energetika ulgamlary inženerligi', kk: 'Энергетикалық жүйелер инженериясы', ky: 'Энергетикалык системалар инженериясы', zh: '能源系统工程', bg: 'Енергийни системи инженерия', ur: 'انرجی سسٹمز انجینئرنگ', uz: 'Energiya tizimlari muhandisligi', sw: 'Uhandisi wa Mifumo ya Nishati', so: 'Injineeriyada Nidaamyada Tamarta', id: 'Teknik Sistem Energi' },
    degreeLevel: 'bachelor',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-eng-genetics',
    slug: 'genetics-and-bioengineering',
    name: { en: 'Genetics and Bioengineering', tr: 'Genetik ve Biyomühendislik', az: 'Genetika və Biomühəndislik', ru: 'Генетика и биоинженерия', de: 'Genetik und Bioingenieurwesen', fr: 'Génétique et bioingénierie', fa: 'ژنتیک و بیومهندسی', ar: 'علم الوراثة والهندسة الحيوية', tk: 'Genetika we bioinženerlik', kk: 'Генетика және биоинженерия', ky: 'Генетика жана биоинженерия', zh: '遗传学与生物工程', bg: 'Генетика и биоинженерство', ur: 'جینیات اور بائیو انجینئرنگ', uz: 'Genetika va bioinjeneriya', sw: 'Jenetiki na Uhandisi wa Baiolojia', so: 'Hiddo-sidka iyo Bioinjineeriyada', id: 'Genetika dan Bioengineering' },
    degreeLevel: 'bachelor',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-eng-petroleum',
    slug: 'petroleum-engineering',
    name: { en: 'Petroleum Engineering', tr: 'Petrol ve Doğal Gaz Mühendisliği', az: 'Neft və Qaz Mühəndisliyi', ru: 'Нефтегазовая инженерия', de: 'Erdöl- und Erdgastechnik', fr: 'Génie pétrolier', fa: 'مهندسی نفت', ar: 'هندسة البترول', tk: 'Neft we gaz inženerligi', kk: 'Мұнай инженериясы', ky: 'Мунай инженериясы', zh: '石油工程', bg: 'Петролно инженерство', ur: 'پیٹرولیم انجینئرنگ', uz: 'Neft muhandisligi', sw: 'Uhandisi wa Mafuta', so: 'Injineeriyada Batroolka', id: 'Teknik Perminyakan' },
    degreeLevel: 'bachelor',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-eng-environmental',
    slug: 'environmental-engineering',
    name: { en: 'Environmental Engineering', tr: 'Çevre Mühendisliği', az: 'Ekologiya Mühəndisliyi', ru: 'Экологическая инженерия', de: 'Umwelttechnik', fr: 'Génie de l’environnement', fa: 'مهندسی محیط زیست', ar: 'الهندسة البيئية', tk: 'Daşky gurşaw inženerligi', kk: 'Қоршаған орта инженериясы', ky: 'Айлана-чөйрө инженериясы', zh: '环境工程', bg: 'Екологично инженерство', ur: 'ماحولیاتی انجینئرنگ', uz: 'Atrof-muhit muhandisligi', sw: 'Uhandisi wa Mazingira', so: 'Injineeriyada Deegaanka', id: 'Teknik Lingkungan' },
    degreeLevel: 'bachelor',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-cs-data-science',
    slug: 'data-science',
    name: { en: 'Data Science', tr: 'Veri Bilimi', az: 'Verilənlər Elmi', ru: 'Наука о данных', de: 'Datenwissenschaft', fr: 'Science des données', fa: 'علم داده', ar: 'علم البيانات', tk: 'Maglumat ylmy', kk: 'Деректер ғылымы', ky: 'Маалымат илими', zh: '数据科学', bg: 'Наука за данни', ur: 'ڈیٹا سائنس', uz: 'Ma’lumotlar fani', sw: 'Sayansi ya Takwimu', so: 'Sayniska Xogta', id: 'Ilmu Data' },
    degreeLevel: 'bachelor',
    categorySlug: 'computer-science',
    durationYears: 4,
  },
  {
    id: 'p-cs-cybersecurity',
    slug: 'cybersecurity',
    name: { en: 'Cybersecurity', tr: 'Siber Güvenlik', az: 'Kibertəhlükəsizlik', ru: 'Кибербезопасность', de: 'Cybersecurity', fr: 'Cybersécurité', fa: 'امنیت سایبری', ar: 'الأمن السيبراني', tk: 'Kiberhowpsuzlyk', kk: 'Киберқауіпсіздік', ky: 'Киберкоопсуздук', zh: '网络安全', bg: 'Киберсигурност', ur: 'سائبر سیکیورٹی', uz: 'Kiberxavfsizlik', sw: 'Usalama wa Mtandao', so: 'Amniga Internetka', id: 'Keamanan Siber' },
    degreeLevel: 'bachelor',
    categorySlug: 'computer-science',
    durationYears: 4,
  },
  {
    id: 'p-cs-info-systems',
    slug: 'information-systems',
    name: { en: 'Information Systems', tr: 'Bilişim Sistemleri', az: 'İnformasiya Sistemləri', ru: 'Информационные системы', de: 'Informationssysteme', fr: 'Systèmes d’information', fa: 'سیستمهای اطلاعاتی', ar: 'نظم المعلومات', tk: 'Maglumat ulgamlary', kk: 'Ақпараттық жүйелер', ky: 'Маалымат системалары', zh: '信息系统', bg: 'Информационни системи', ur: 'انفارمیشن سسٹمز', uz: 'Axborot tizimlari', sw: 'Mifumo ya Habari', so: 'Nidaamyada Macluumaadka', id: 'Sistem Informasi' },
    degreeLevel: 'bachelor',
    categorySlug: 'computer-science',
    durationYears: 4,
  },
  {
    id: 'p-cs-game-dev',
    slug: 'game-development',
    name: { en: 'Game Development', tr: 'Oyun Geliştirme', az: 'Oyun Yaradılması', ru: 'Разработка игр', de: 'Spieleentwicklung', fr: 'Développement de jeux', fa: 'توسعه بازی', ar: 'تطوير الألعاب', tk: 'Oýun işläp düzmek', kk: 'Ойын жасау', ky: 'Оюн иштеп чыгуу', zh: '游戏开发', bg: 'Разработка на игри', ur: 'گیم ڈویلپمنٹ', uz: 'O’yin yaratish', sw: 'Uendelezaji wa Michezo', so: 'Horuminta Ciyaaraha', id: 'Pengembangan Game' },
    degreeLevel: 'bachelor',
    categorySlug: 'computer-science',
    durationYears: 4,
  },
  {
    id: 'p-bus-int-trade',
    slug: 'international-trade',
    name: { en: 'International Trade', tr: 'Uluslararası Ticaret', az: 'Beynəlxalq Ticarət', ru: 'Международная торговля', de: 'Internationaler Handel', fr: 'Commerce international', fa: 'تجارت بینالملل', ar: 'التجارة الدولية', tk: 'Halkara söwda', kk: 'Халықаралық сауда', ky: 'Эл аралык соода', zh: '国际贸易', bg: 'Международна търговия', ur: 'بین الاقوامی تجارت', uz: 'Xalqaro savdo', sw: 'Biashara ya Kimataifa', so: 'Ganacsiga Caalamiga', id: 'Perdagangan Internasional' },
    degreeLevel: 'bachelor',
    categorySlug: 'business',
    durationYears: 4,
  },
  {
    id: 'p-bus-marketing',
    slug: 'marketing',
    name: { en: 'Marketing', tr: 'Pazarlama', az: 'Marketinq', ru: 'Маркетинг', de: 'Marketing', fr: 'Marketing', fa: 'بازاریابی', ar: 'التسويق', tk: 'Marketing', kk: 'Маркетинг', ky: 'Маркетинг', zh: '市场营销', bg: 'Маркетинг', ur: 'مارکیٹنگ', uz: 'Marketing', sw: 'Masoko', so: 'Suuqa', id: 'Pemasaran' },
    degreeLevel: 'bachelor',
    categorySlug: 'business',
    durationYears: 4,
  },
  {
    id: 'p-bus-economics',
    slug: 'economics',
    name: { en: 'Economics', tr: 'Ekonomi', az: 'İqtisadiyyat', ru: 'Экономика', de: 'Volkswirtschaftslehre', fr: 'Économie', fa: 'اقتصاد', ar: 'الاقتصاد', tk: 'Ykdysadyýet', kk: 'Экономика', ky: 'Экономика', zh: '经济学', bg: 'Икономика', ur: 'معاشیات', uz: 'Iqtisodiyot', sw: 'Uchumi', so: 'Dhaqaalaha', id: 'Ekonomi' },
    degreeLevel: 'bachelor',
    categorySlug: 'business',
    durationYears: 4,
  },
  {
    id: 'p-bus-finance',
    slug: 'finance',
    name: { en: 'Finance', tr: 'Finans', az: 'Maliyyə', ru: 'Финансы', de: 'Finanzwesen', fr: 'Finance', fa: 'مالیه', ar: 'المالية', tk: 'Maliýe', kk: 'Қаржы', ky: 'Каржы', zh: '金融学', bg: 'Финанси', ur: 'فنانس', uz: 'Moliya', sw: 'Fedha', so: 'Maaliyadda', id: 'Keuangan' },
    degreeLevel: 'bachelor',
    categorySlug: 'business',
    durationYears: 4,
  },
  {
    id: 'p-bus-accounting',
    slug: 'accounting',
    name: { en: 'Accounting', tr: 'Muhasebe', az: 'Mühasibat', ru: 'Бухгалтерский учёт', de: 'Buchhaltung', fr: 'Comptabilité', fa: 'حسابداری', ar: 'المحاسبة', tk: 'Bukgalteriýa', kk: 'Бухгалтерлік есеп', ky: 'Бухгалтердик эсеп', zh: '会计学', bg: 'Счетоводство', ur: 'اکاؤنٹنگ', uz: 'Buxgalteriya', sw: 'Uhasibu', so: 'Xisaabinta', id: 'Akuntansi' },
    degreeLevel: 'bachelor',
    categorySlug: 'business',
    durationYears: 4,
  },
  {
    id: 'p-bus-hrm',
    slug: 'human-resources-management',
    name: { en: 'Human Resources Management', tr: 'İnsan Kaynakları Yönetimi', az: 'İnsan Resurslarının İdarəedilməsi', ru: 'Управление человеческими ресурсами', de: 'Personalmanagement', fr: 'Gestion des ressources humaines', fa: 'مدیریت منابع انسانی', ar: 'إدارة الموارد البشرية', tk: 'Adam resurslaryny dolandyryş', kk: 'Адами ресурстарды басқару', ky: 'Адам ресурстарын башкаруу', zh: '人力资源管理', bg: 'Управление на човешките ресурси', ur: 'ہیومن ریسورس مینجمنٹ', uz: 'Inson resurslarini boshqarish', sw: 'Usimamizi wa Rasilimali Watu', so: 'Maamulka Kheyraadka Aadanaha', id: 'Manajemen Sumber Daya Manusia' },
    degreeLevel: 'bachelor',
    categorySlug: 'business',
    durationYears: 4,
  },
  {
    id: 'p-bus-scm',
    slug: 'supply-chain-management',
    name: { en: 'Supply Chain Management', tr: 'Tedarik Zinciri Yönetimi', az: 'Təchizat Zəncirinin İdarəedilməsi', ru: 'Управление цепочками поставок', de: 'Lieferkettenmanagement', fr: 'Gestion de la chaîne d’approvisionnement', fa: 'مدیریت زنجیره تامین', ar: 'إدارة سلسلة التوريد', tk: 'Üpjünçilik zynjyryny dolandyryş', kk: 'Жабдықтау тізбегін басқару', ky: 'Камсыздоо чынжырын башкаруу', zh: '供应链管理', bg: 'Управление на веригата на доставки', ur: 'سپلائی چین مینجمنٹ', uz: 'Ta’minot zanjiri boshqaruvi', sw: 'Usimamizi wa Msururu wa Ugavi', so: 'Maamulka Silsilada Saadka', id: 'Manajemen Rantai Pasok' },
    degreeLevel: 'bachelor',
    categorySlug: 'business',
    durationYears: 4,
  },
  {
    id: 'p-tour-tourism',
    slug: 'tourism-management',
    name: { en: 'Tourism Management', tr: 'Turizm İşletmeciliği', az: 'Turizm İdarəetməsi', ru: 'Менеджмент в туризме', de: 'Tourismusmanagement', fr: 'Management du tourisme', fa: 'مدیریت گردشگری', ar: 'إدارة السياحة', tk: 'Syýahatçylyk dolandyryşy', kk: 'Туризмді басқару', ky: 'Туризмди башкаруу', zh: '旅游管理', bg: 'Туристически мениджмънт', ur: 'ٹورازم مینجمنٹ', uz: 'Turizm boshqaruvi', sw: 'Usimamizi wa Utalii', so: 'Maamulka Dalooska', id: 'Manajemen Pariwisata' },
    degreeLevel: 'bachelor',
    categorySlug: 'tourism',
    durationYears: 4,
  },
  {
    id: 'p-tour-hotel',
    slug: 'hotel-management',
    name: { en: 'Hotel Management', tr: 'Otel İşletmeciliği', az: 'Otel İdarəetməsi', ru: 'Гостиничный менеджмент', de: 'Hotelmanagement', fr: 'Management hôtelier', fa: 'مدیریت هتل', ar: 'إدارة الفنادق', tk: 'Myhmanhana dolandyryşy', kk: 'Қонақ үй менеджменті', ky: 'Мейманкана башкаруу', zh: '酒店管理', bg: 'Хотел мениджмънт', ur: 'ہوٹل مینجمنٹ', uz: 'Mehmonxona boshqaruvi', sw: 'Usimamizi wa Hoteli', so: 'Maamulka Hoteelada', id: 'Manajemen Perhotelan' },
    degreeLevel: 'bachelor',
    categorySlug: 'tourism',
    durationYears: 4,
  },
  {
    id: 'p-tour-gastronomy',
    slug: 'gastronomy-and-culinary-arts',
    name: { en: 'Gastronomy and Culinary Arts', tr: 'Gastronomi ve Mutfak Sanatları', az: 'Qastronomiya və Aşpazlıq Sənəti', ru: 'Гастрономия и кулинарное искусство', de: 'Gastronomie und Kochkunst', fr: 'Gastronomie et arts culinaires', fa: 'گاسترونومی و هنر آشپزی', ar: 'فن الطهي والغذاء', tk: 'Gastronomiýa we aşpezlik sungaty', kk: 'Гастрономия және аспаздық өнер', ky: 'Гастрономия жана ашпозчулук өнөрү', zh: '美食学与烹饪艺术', bg: 'Гастрономия и кулинарно изкуство', ur: 'گاسٹرونومی اور کھانا پکانے کے فنون', uz: 'Gastronomiya va oshpazlik san’ati', sw: 'Gastronomia na Sanaa za Upishi', so: 'Gastronomiyada iyo Fanka Cuntada', id: 'Gastronomi dan Seni Kuliner' },
    degreeLevel: 'bachelor',
    categorySlug: 'tourism',
    durationYears: 4,
  },
  {
    id: 'p-health-pharmacy',
    slug: 'pharmacy',
    name: { en: 'Pharmacy', tr: 'Eczacılık', az: 'Farmasiya', ru: 'Фармация', de: 'Pharmazie', fr: 'Pharmacie', fa: 'داروسازی', ar: 'الصيدلة', tk: 'Farmasiýa', kk: 'Фармация', ky: 'Фармация', zh: '药学', bg: 'Фармация', ur: 'فارمیسی', uz: 'Farmatsiya', sw: 'Famasia', so: 'Farmasiyada', id: 'Farmasi' },
    degreeLevel: 'bachelor',
    categorySlug: 'health-sciences',
    durationYears: 5,
  },
  {
    id: 'p-health-nursing',
    slug: 'nursing',
    name: { en: 'Nursing', tr: 'Hemşirelik', az: 'Hemşirəlik', ru: 'Сестринское дело', de: 'Pflegewissenschaft', fr: 'Soins infirmiers', fa: 'پرستاری', ar: 'التمريض', tk: 'Şepagat uýasy', kk: 'Мейірбике ісі', ky: 'Медайымдык иш', zh: '护理学', bg: 'Сестрински грижи', ur: 'نرسنگ', uz: 'Hamshiralik', sw: 'Uuguzi', so: 'Kalkaalinta', id: 'Keperawatan' },
    degreeLevel: 'bachelor',
    categorySlug: 'health-sciences',
    durationYears: 4,
  },
  {
    id: 'p-health-physio',
    slug: 'physiotherapy',
    name: { en: 'Physiotherapy', tr: 'Fizyoterapi', az: 'Fizioterapiya', ru: 'Физиотерапия', de: 'Physiotherapie', fr: 'Kinésithérapie', fa: 'فیزیوتراپی', ar: 'العلاج الطبيعي', tk: 'Fizioterapiýa', kk: 'Физиотерапия', ky: 'Физиотерапия', zh: '物理治疗', bg: 'Физиотерапия', ur: 'فزیوتھراپی', uz: 'Fizioterapiya', sw: 'Tiba ya Kimwili', so: 'Fisiyoterabiyada', id: 'Fisioterapi' },
    degreeLevel: 'bachelor',
    categorySlug: 'health-sciences',
    durationYears: 4,
  },
  {
    id: 'p-health-nutrition',
    slug: 'nutrition-and-dietetics',
    name: { en: 'Nutrition and Dietetics', tr: 'Beslenme ve Diyetetik', az: 'Qidalanma və Dietetika', ru: 'Питание и диетология', de: 'Ernährungswissenschaft', fr: 'Nutrition et diététique', fa: 'تغذیه و رژیمشناسی', ar: 'التغذية والحمية', tk: 'Iýmitleniş we dietetika', kk: 'Тамақтану және диетология', ky: 'Тамактануу жана диетология', zh: '营养与饮食学', bg: 'Хранене и диететика', ur: 'غذائیت اور ڈائیٹکس', uz: 'Oziqlanish va dietetika', sw: 'Lishe na Dietetics', so: 'Nafaqada iyo Cuntada', id: 'Nutrisi dan Dietetika' },
    degreeLevel: 'bachelor',
    categorySlug: 'health-sciences',
    durationYears: 4,
  },
  {
    id: 'p-health-psychology',
    slug: 'psychology',
    name: { en: 'Psychology', tr: 'Psikoloji', az: 'Psixologiya', ru: 'Психология', de: 'Psychologie', fr: 'Psychologie', fa: 'روانشناسی', ar: 'علم النفس', tk: 'Psihologiýa', kk: 'Психология', ky: 'Психология', zh: '心理学', bg: 'Психология', ur: 'نفسیات', uz: 'Psixologiya', sw: 'Saikolojia', so: 'Cilmi-nafsiga', id: 'Psikologi' },
    degreeLevel: 'bachelor',
    categorySlug: 'health-sciences',
    durationYears: 4,
  },
  {
    id: 'p-dent-prosthetics',
    slug: 'dental-prosthetics',
    name: { en: 'Dental Prosthetics', tr: 'Diş Protez', az: 'Diş Protezləri', ru: 'Зубное протезирование', de: 'Zahntechnik', fr: 'Prothèse dentaire', fa: 'پروتز دندان', ar: 'تعويضات الأسنان', tk: 'Diş protezi', kk: 'Тіс протезі', ky: 'Тиш протези', zh: '牙科修复', bg: 'Зъбопротезиране', ur: 'دندان سازی', uz: 'Tish protezlari', sw: 'Prosthetiki ya Meno', so: 'Ilgaxa Ilkaha', id: 'Prostetik Gigi' },
    degreeLevel: 'associate',
    categorySlug: 'dentistry',
    durationYears: 2,
  },
  {
    id: 'p-health-biomed-tech',
    slug: 'biomedical-technology',
    name: { en: 'Biomedical Technology', tr: 'Biyomedikal Teknoloji', az: 'Biomedikal Texnologiyalar', ru: 'Биомедицинские технологии', de: 'Biomedizintechnik', fr: 'Technologie biomédicale', fa: 'فناوری پزشکی', ar: 'التكنولوجيا الطبية الحيوية', tk: 'Biomedisin tehnologiýasy', kk: 'Биомедициналық технология', ky: 'Биомедициналык технология', zh: '生物医学技术', bg: 'Биомедицинска технология', ur: 'بایو میڈیکل ٹیکنالوجی', uz: 'Biomeditsina texnologiyasi', sw: 'Teknolojia ya Biomedical', so: 'Tiknoolajiyada Caafimaadka', id: 'Teknologi Biomedis' },
    degreeLevel: 'bachelor',
    categorySlug: 'health-sciences',
    durationYears: 4,
  },
  {
    id: 'p-soc-political',
    slug: 'political-science',
    name: { en: 'Political Science', tr: 'Siyaset Bilimi', az: 'Siyasət Elmi', ru: 'Политология', de: 'Politikwissenschaft', fr: 'Science politique', fa: 'علوم سیاسی', ar: 'العلوم السياسية', tk: 'Syýasy ylymlar', kk: 'Саясаттану', ky: 'Саясат илими', zh: '政治学', bg: 'Политология', ur: 'پولیٹیکل سائنس', uz: 'Siyosatshunoslik', sw: 'Sayansi ya Siasa', so: 'Cilimka Siyaasadda', id: 'Ilmu Politik' },
    degreeLevel: 'bachelor',
    categorySlug: 'social-sciences',
    durationYears: 4,
  },
  {
    id: 'p-soc-sociology',
    slug: 'sociology',
    name: { en: 'Sociology', tr: 'Sosyoloji', az: 'Sosiologiya', ru: 'Социология', de: 'Soziologie', fr: 'Sociologie', fa: 'جامعهشناسی', ar: 'علم الاجتماع', tk: 'Sosiologiýa', kk: 'Әлеуметтану', ky: 'Социология', zh: '社会学', bg: 'Социология', ur: 'سوشیالوجی', uz: 'Sotsiologiya', sw: 'Sosholojia', so: 'Cilimka Bulshada', id: 'Sosiologi' },
    degreeLevel: 'bachelor',
    categorySlug: 'social-sciences',
    durationYears: 4,
  },
  {
    id: 'p-soc-int-relations',
    slug: 'international-relations-social',
    name: { en: 'International Relations', tr: 'Uluslararası İlişkiler', az: 'Beynəlxalq Münasibətlər', ru: 'Международные отношения', de: 'Internationale Beziehungen', fr: 'Relations internationales', fa: 'روابط بینالملل', ar: 'العلاقات الدولية', tk: 'Halkara gatnaşyklar', kk: 'Халықаралық қатынастар', ky: 'Эл аралык мамилелер', zh: '国际关系', bg: 'Международни отношения', ur: 'بین الاقوامی تعلقات', uz: 'Xalqaro munosabatlar', sw: 'Mahusiano ya Kimataifa', so: 'Xiriirka Caalamiga', id: 'Hubungan Internasional' },
    degreeLevel: 'bachelor',
    categorySlug: 'social-sciences',
    durationYears: 4,
  },
  {
    id: 'p-soc-public-admin',
    slug: 'public-administration',
    name: { en: 'Public Administration', tr: 'Kamu Yönetimi', az: 'Dövlət İdarəetməsi', ru: 'Государственное управление', de: 'Öffentliche Verwaltung', fr: 'Administration publique', fa: 'مدیریت دولتی', ar: 'الإدارة العامة', tk: 'Döwlet dolandyryşy', kk: 'Мемлекеттік басқару', ky: 'Мамлекеттик башкаруу', zh: '公共管理', bg: 'Публична администрация', ur: 'پبلک ایڈمنسٹریشن', uz: 'Davlat boshqaruvi', sw: 'Utawala wa Umma', so: 'Maamulka Guud', id: 'Administrasi Publik' },
    degreeLevel: 'bachelor',
    categorySlug: 'social-sciences',
    durationYears: 4,
  },
  {
    id: 'p-hum-history',
    slug: 'history',
    name: { en: 'History', tr: 'Tarih', az: 'Tarix', ru: 'История', de: 'Geschichte', fr: 'Histoire', fa: 'تاریخ', ar: 'التاريخ', tk: 'Taryh', kk: 'Тарих', ky: 'Тарых', zh: '历史学', bg: 'История', ur: 'تاریخ', uz: 'Tarix', sw: 'Historia', so: 'Taariikhda', id: 'Sejarah' },
    degreeLevel: 'bachelor',
    categorySlug: 'humanities',
    durationYears: 4,
  },
  {
    id: 'p-hum-literature',
    slug: 'turkish-language-and-literature',
    name: { en: 'Turkish Language and Literature', tr: 'Türk Dili ve Edebiyatı', az: 'Türk Dili və Ədəbiyyatı', ru: 'Турецкий язык и литература', de: 'Türkische Sprache und Literatur', fr: 'Langue et littérature turques', fa: 'زبان و ادبیات ترکی', ar: 'اللغة التركية وآدابها', tk: 'Türk dili we edebiýaty', kk: 'Түрік тілі мен әдебиеті', ky: 'Түрк тили жана адабияты', zh: '土耳其语言与文学', bg: 'Турски език и литература', ur: 'ترک زبان اور ادب', uz: 'Turk tili va adabiyoti', sw: 'Lugha na Fasihi ya Kituruki', so: 'Afafka iyo Suugaanta Turkiga', id: 'Bahasa dan Sastra Turki' },
    degreeLevel: 'bachelor',
    categorySlug: 'humanities',
    durationYears: 4,
  },
  {
    id: 'p-hum-philosophy',
    slug: 'philosophy',
    name: { en: 'Philosophy', tr: 'Felsefe', az: 'Fəlsəfə', ru: 'Философия', de: 'Philosophie', fr: 'Philosophie', fa: 'فلسفه', ar: 'الفلسفة', tk: 'Filosofiýa', kk: 'Философия', ky: 'Философия', zh: '哲学', bg: 'Философия', ur: 'فلسفہ', uz: 'Falsafa', sw: 'Falsafa', so: 'Falsafada', id: 'Filsafat' },
    degreeLevel: 'bachelor',
    categorySlug: 'humanities',
    durationYears: 4,
  },
  {
    id: 'p-hum-translation',
    slug: 'translation-and-interpreting',
    name: { en: 'Translation and Interpreting', tr: 'Mütercimlik ve Tercümanlık', az: 'Tərcümə və Təfsir', ru: 'Перевод и устный перевод', de: 'Übersetzung und Dolmetschen', fr: 'Traduction et interprétation', fa: 'مترجمی و ترجمه شفاهی', ar: 'الترجمة والترجمة الفورية', tk: 'Tercime we terjimeçilik', kk: 'Аударма және аудармашылық', ky: 'Котормо жана котормочулук', zh: '翻译与口译', bg: 'Превод и устен превод', ur: 'ترجمہ اور ترجمانی', uz: 'Tarjima va tarjimonlik', sw: 'Tafsiri na Ukalimani', so: 'Turjumaadda iyo Fasiraadda', id: 'Penerjemahan dan Interpretasi' },
    degreeLevel: 'bachelor',
    categorySlug: 'humanities',
    durationYears: 4,
  },
  {
    id: 'p-com-journalism',
    slug: 'journalism',
    name: { en: 'Journalism', tr: 'Gazetecilik', az: 'Jurnalistika', ru: 'Журналистика', de: 'Journalismus', fr: 'Journalisme', fa: 'روزنامهنگاری', ar: 'الصحافة', tk: 'Žurnalistika', kk: 'Журналистика', ky: 'Журналистика', zh: '新闻学', bg: 'Журналистика', ur: 'صحافت', uz: 'Jurnalistika', sw: 'Uandishi wa Habari', so: 'Saxaafadda', id: 'Jurnalistik' },
    degreeLevel: 'bachelor',
    categorySlug: 'communication',
    durationYears: 4,
  },
  {
    id: 'p-com-pr',
    slug: 'public-relations',
    name: { en: 'Public Relations', tr: 'Halkla İlişkiler', az: 'İctimai Əlaqələr', ru: 'Связи с общественностью', de: 'Öffentlichkeitsarbeit', fr: 'Relations publiques', fa: 'روابط عمومی', ar: 'العلاقات العامة', tk: 'Jemgyýetçilik bilen aragatnaşyk', kk: 'Қоғаммен байланыс', ky: 'Коом менен байланыш', zh: '公共关系', bg: 'Връзки с обществеността', ur: 'پبلک ریلشنز', uz: 'Jamoatchilik bilan aloqalar', sw: 'Mahusiano ya Umma', so: 'Xiriirka Dadweynaha', id: 'Hubungan Masyarakat' },
    degreeLevel: 'bachelor',
    categorySlug: 'communication',
    durationYears: 4,
  },
  {
    id: 'p-com-rtvc',
    slug: 'radio-television-and-cinema',
    name: { en: 'Radio, Television and Cinema', tr: 'Radyo, Televizyon ve Sinema', az: 'Radio, Televiziya və Kino', ru: 'Радио, телевидение и кино', de: 'Radio, Fernsehen und Kino', fr: 'Radio, télévision et cinéma', fa: 'رادیو، تلویزیون و سینما', ar: 'الإذاعة والتلفزيون والسينما', tk: 'Radio, telewideniýe we kino', kk: 'Радио, теледидар және кино', ky: 'Радио, телекөрсөтүү жана кино', zh: '广播电视与电影', bg: 'Радио, телевизия и кино', ur: 'ریڈیو، ٹیلی ویژن اور سنیما', uz: 'Radio, televideniye va kino', sw: 'Redio, Televisheni na Sinema', so: 'Raadiyada, Telefishanka iyo Shineemada', id: 'Radio, Televisi dan Film' },
    degreeLevel: 'bachelor',
    categorySlug: 'communication',
    durationYears: 4,
  },
  {
    id: 'p-com-advertising',
    slug: 'advertising',
    name: { en: 'Advertising', tr: 'Reklamcılık', az: 'Reklamçılıq', ru: 'Реклама', de: 'Werbung', fr: 'Publicité', fa: 'تبلیغات', ar: 'الإعلان', tk: 'Mahabat', kk: 'Жарнама', ky: 'Жарнама', zh: '广告学', bg: 'Реклама', ur: 'ایڈورٹائزنگ', uz: 'Reklama', sw: 'Utangazaji', so: 'Xayeysiinta', id: 'Periklanan' },
    degreeLevel: 'bachelor',
    categorySlug: 'communication',
    durationYears: 4,
  },
  {
    id: 'p-com-new-media',
    slug: 'new-media-and-communication',
    name: { en: 'New Media and Communication', tr: 'Yeni Medya ve İletişim', az: 'Yeni Media və Kommunikasiya', ru: 'Новые медиа и коммуникации', de: 'Neue Medien und Kommunikation', fr: 'Nouveaux médias et communication', fa: 'رسانههای نوین و ارتباطات', ar: 'الإعلام الجديد والاتصال', tk: 'Täze media we aragatnaşyk', kk: 'Жаңа медиа және коммуникация', ky: 'Жаңы медиа жана коммуникация', zh: '新媒体与传播', bg: 'Нови медии и комуникации', ur: 'نیو میڈیا اور کمیونیکیشن', uz: 'Yangi media va kommunikatsiya', sw: 'Vyombo Mpya vya Habari na Mawasiliano', so: 'Warbaahinta Cusub iyo Isgaarsiinta', id: 'Media Baru dan Komunikasi' },
    degreeLevel: 'bachelor',
    categorySlug: 'communication',
    durationYears: 4,
  },
  {
    id: 'p-nat-mathematics',
    slug: 'mathematics',
    name: { en: 'Mathematics', tr: 'Matematik', az: 'Riyaziyyat', ru: 'Математика', de: 'Mathematik', fr: 'Mathématiques', fa: 'ریاضیات', ar: 'الرياضيات', tk: 'Matematika', kk: 'Математика', ky: 'Математика', zh: '数学', bg: 'Математика', ur: 'ریاضیات', uz: 'Matematika', sw: 'Hisabati', so: 'Xisaabta', id: 'Matematika' },
    degreeLevel: 'bachelor',
    categorySlug: 'natural-sciences',
    durationYears: 4,
  },
  {
    id: 'p-nat-physics',
    slug: 'physics',
    name: { en: 'Physics', tr: 'Fizik', az: 'Fizika', ru: 'Физика', de: 'Physik', fr: 'Physique', fa: 'فیزیک', ar: 'الفيزياء', tk: 'Fizika', kk: 'Физика', ky: 'Физика', zh: '物理学', bg: 'Физика', ur: 'فزکس', uz: 'Fizika', sw: 'Fizikia', so: 'Fiisigiska', id: 'Fisika' },
    degreeLevel: 'bachelor',
    categorySlug: 'natural-sciences',
    durationYears: 4,
  },
  {
    id: 'p-nat-chemistry',
    slug: 'chemistry',
    name: { en: 'Chemistry', tr: 'Kimya', az: 'Kimya', ru: 'Химия', de: 'Chemie', fr: 'Chimie', fa: 'شیمی', ar: 'الكيمياء', tk: 'Himiýa', kk: 'Химия', ky: 'Химия', zh: '化学', bg: 'Химия', ur: 'کیمسٹری', uz: 'Kimyo', sw: 'Kemia', so: 'Kiimikada', id: 'Kimia' },
    degreeLevel: 'bachelor',
    categorySlug: 'natural-sciences',
    durationYears: 4,
  },
  {
    id: 'p-nat-biology',
    slug: 'biology',
    name: { en: 'Biology', tr: 'Biyoloji', az: 'Biologiya', ru: 'Биология', de: 'Biologie', fr: 'Biologie', fa: 'زیستشناسی', ar: 'علم الأحياء', tk: 'Biologiýa', kk: 'Биология', ky: 'Биология', zh: '生物学', bg: 'Биология', ur: 'حیاتیات', uz: 'Biologiya', sw: 'Baiolojia', so: 'Bayoloji', id: 'Biologi' },
    degreeLevel: 'bachelor',
    categorySlug: 'natural-sciences',
    durationYears: 4,
  },
  {
    id: 'p-nat-molbio',
    slug: 'molecular-biology-and-genetics',
    name: { en: 'Molecular Biology and Genetics', tr: 'Moleküler Biyoloji ve Genetik', az: 'Molekulyar Biologiya və Genetika', ru: 'Молекулярная биология и генетика', de: 'Molekularbiologie und Genetik', fr: 'Biologie moléculaire et génétique', fa: 'زیستشناسی مولکولی و ژنتیک', ar: 'البيولوجيا الجزيئية وعلم الوراثة', tk: 'Molekulýar biologiýa we genetika', kk: 'Молекулалық биология және генетика', ky: 'Молекулалык биология жана генетика', zh: '分子生物学与遗传学', bg: 'Молекулярна биология и генетика', ur: 'مالیکیولر بائیولوجی اور جینیٹکس', uz: 'Molekulyar biologiya va genetika', sw: 'Baiolojia ya Molekuli na Jenetiki', so: 'Bayolojiyada Molecular iyo Hidde-sidka', id: 'Biologi Molekuler dan Genetika' },
    degreeLevel: 'bachelor',
    categorySlug: 'natural-sciences',
    durationYears: 4,
  },
  {
    id: 'p-arts-graphic',
    slug: 'graphic-design',
    name: { en: 'Graphic Design', tr: 'Grafik Tasarım', az: 'Qrafik Dizayn', ru: 'Графический дизайн', de: 'Grafikdesign', fr: 'Design graphique', fa: 'طراحی گرافیک', ar: 'التصميم الجرافيكي', tk: 'Grafik dizaýn', kk: 'Графикалық дизайн', ky: 'Графикалык дизайн', zh: '平面设计', bg: 'Графичен дизайн', ur: 'گرافک ڈیزائن', uz: 'Grafik dizayn', sw: 'Ubunifu wa Picha', so: 'Naqshadaynta Garaafiga', id: 'Desain Grafis' },
    degreeLevel: 'bachelor',
    categorySlug: 'arts',
    durationYears: 4,
  },
  {
    id: 'p-arts-interior',
    slug: 'interior-architecture',
    name: { en: 'Interior Architecture', tr: 'İç Mimarlık', az: 'İnteryer Memarlığı', ru: 'Дизайн интерьера', de: 'Innenarchitektur', fr: 'Architecture d’intérieur', fa: 'معماری داخلی', ar: 'العمارة الداخلية', tk: 'Içki arhitektura', kk: 'Ішкі сәулет', ky: 'Ички архитектура', zh: '室内建筑', bg: 'Интериорна архитектура', ur: 'انٹیریئر آرکیٹیکچر', uz: 'Ichki arxitektura', sw: 'Usanifu wa Mambo ya Ndani', so: 'Naqshada Gudaha', id: 'Arsitektur Interior' },
    degreeLevel: 'bachelor',
    categorySlug: 'arts',
    durationYears: 4,
  },
  {
    id: 'p-arts-fashion',
    slug: 'fashion-design',
    name: { en: 'Fashion Design', tr: 'Moda Tasarımı', az: 'Moda Dizaynı', ru: 'Дизайн одежды', de: 'Modedesign', fr: 'Design de mode', fa: 'طراحی مد', ar: 'تصميم الأزياء', tk: 'Moda dizaýny', kk: 'Сән дизайны', ky: 'Мода дизайны', zh: '时装设计', bg: 'Моден дизайн', ur: 'فیشن ڈیزائن', uz: 'Moda dizayni', sw: 'Ubunifu wa Mitindo', so: 'Naqshadaynta Moodada', id: 'Desain Mode' },
    degreeLevel: 'bachelor',
    categorySlug: 'arts',
    durationYears: 4,
  },
  {
    id: 'p-arts-music',
    slug: 'music',
    name: { en: 'Music', tr: 'Müzik', az: 'Musiqi', ru: 'Музыка', de: 'Musik', fr: 'Musique', fa: 'موسیقی', ar: 'الموسيقى', tk: 'Saz', kk: 'Музыка', ky: 'Музыка', zh: '音乐学', bg: 'Музика', ur: 'موسیقی', uz: 'Musiqa', sw: 'Muziki', so: 'Muusikada', id: 'Musik' },
    degreeLevel: 'bachelor',
    categorySlug: 'arts',
    durationYears: 4,
  },
  {
    id: 'p-arts-cinema',
    slug: 'cinema-and-television',
    name: { en: 'Cinema and Television', tr: 'Sinema ve Televizyon', az: 'Kino və Televiziya', ru: 'Кино и телевидение', de: 'Film und Fernsehen', fr: 'Cinéma et télévision', fa: 'سینما و تلویزیون', ar: 'السينما والتلفزيون', tk: 'Kino we telewideniýe', kk: 'Кино және теледидар', ky: 'Кино жана телекөрсөтүү', zh: '电影与电视', bg: 'Кино и телевизия', ur: 'سنما اور ٹیلی ویژن', uz: 'Kino va televideniye', sw: 'Sinema na Televisheni', so: 'Shineemada iyo Telefishanka', id: 'Perfilman dan Televisi' },
    degreeLevel: 'bachelor',
    categorySlug: 'arts',
    durationYears: 4,
  },
  {
    id: 'p-agri-food-eng',
    slug: 'food-engineering',
    name: { en: 'Food Engineering', tr: 'Gıda Mühendisliği', az: 'Qida Mühəndisliyi', ru: 'Пищевая инженерия', de: 'Lebensmitteltechnik', fr: 'Génie alimentaire', fa: 'مهندسی صنایع غذایی', ar: 'هندسة الأغذية', tk: 'Iýmit inženerligi', kk: 'Тамақ өнімдері инженериясы', ky: 'Азык-түлүк инженериясы', zh: '食品工程', bg: 'Хранително инженерство', ur: 'فوڈ انجینئرنگ', uz: 'Oziq-ovqat muhandisligi', sw: 'Uhandisi wa Chakula', so: 'Injineeriyada Cuntada', id: 'Teknik Pangan' },
    degreeLevel: 'bachelor',
    categorySlug: 'agriculture',
    durationYears: 4,
  },
  {
    id: 'p-agri-agri-eng',
    slug: 'agricultural-engineering',
    name: { en: 'Agricultural Engineering', tr: 'Tarım Mühendisliği', az: 'Kənd Təsərrüfatı Mühəndisliyi', ru: 'Сельскохозяйственная инженерия', de: 'Agrartechnik', fr: 'Génie agricole', fa: 'مهندسی کشاورزی', ar: 'الهندسة الزراعية', tk: 'Oba hojalyk inženerligi', kk: 'Ауыл шаруашылығы инженериясы', ky: 'Айыл чарба инженериясы', zh: '农业工程', bg: 'Селскостопанско инженерство', ur: 'زرعی انجینئرنگ', uz: 'Qishloq xo’jaligi muhandisligi', sw: 'Uhandisi wa Kilimo', so: 'Injineeriyada Beeraha', id: 'Teknik Pertanian' },
    degreeLevel: 'bachelor',
    categorySlug: 'agriculture',
    durationYears: 4,
  },
  {
    id: 'p-bus-mba-exec',
    slug: 'executive-mba',
    name: { en: 'Executive MBA', tr: 'Yönetici MBA', az: 'İcraçı MBA', ru: 'Executive MBA', de: 'Executive MBA', fr: 'Executive MBA', fa: 'MBA مدیریتی', ar: 'ماجستير تنفيذي', tk: 'Executive MBA', kk: 'Executive MBA', ky: 'Executive MBA', zh: '高级工商管理硕士', bg: 'Executive MBA', ur: 'ایگزیکٹو ایم بی اے', uz: 'Executive MBA', sw: 'Executive MBA', so: 'Executive MBA', id: 'Executive MBA' },
    degreeLevel: 'master',
    categorySlug: 'business',
    durationYears: 2,
  },
  {
    id: 'p-eng-civil-master',
    slug: 'civil-engineering-master',
    name: { en: 'Civil Engineering (MSc)', tr: 'İnşaat Mühendisliği (YL)', az: 'İnşaat Mühəndisliyi (Magistr)', ru: 'Гражданское строительство (Магистр)', de: 'Bauingenieurwesen (MSc)', fr: 'Génie civil (MSc)', fa: 'مهندسی عمران (کارشناسی ارشد)', ar: 'الهندسة المدنية (ماجستير)', tk: 'Gurluşyk inženerligi (magistr)', kk: 'Құрылыс инженериясы (магистр)', ky: 'Курулуш инженериясы (магистр)', zh: '土木工程（硕士）', bg: 'Строително инженерство (магистър)', ur: 'سول انجینئرنگ (ماسٹر)', uz: 'Qurilish muhandisligi (magistr)', sw: 'Uhandisi wa Ujenzi (MSc)', so: 'Injineeriyada Dhismaha (MSc)', id: 'Teknik Sipil (MSc)' },
    degreeLevel: 'master',
    categorySlug: 'engineering',
    durationYears: 2,
  },
  {
    id: 'p-health-pharmacy-master',
    slug: 'pharmacy-master',
    name: { en: 'Pharmacy (MSc)', tr: 'Eczacılık (YL)', az: 'Farmasiya (Magistr)', ru: 'Фармация (Магистр)', de: 'Pharmazie (MSc)', fr: 'Pharmacie (MSc)', fa: 'داروسازی (کارشناسی ارشد)', ar: 'الصيدلة (ماجستير)', tk: 'Farmasiýa (magistr)', kk: 'Фармация (магистр)', ky: 'Фармация (магистр)', zh: '药学（硕士）', bg: 'Фармация (магистър)', ur: 'فارمیسی (ماسٹر)', uz: 'Farmatsiya (magistr)', sw: 'Famasia (MSc)', so: 'Farmasiyada (MSc)', id: 'Farmasi (MSc)' },
    degreeLevel: 'master',
    categorySlug: 'health-sciences',
    durationYears: 2,
  },
  {
    id: 'p-eng-phd',
    slug: 'engineering-phd',
    name: { en: 'PhD in Engineering', tr: 'Mühendislik Doktorası', az: 'Mühəndislik Doktorantası', ru: 'Докторантура по инженерии', de: 'Promotion im Ingenieurwesen', fr: 'Doctorat en ingénierie', fa: 'دکترای مهندسی', ar: 'دكتوراه في الهندسة', tk: 'Inženerlik doktoranty', kk: 'Инженерия докторантурасы', ky: 'Инженерия докторантурасы', zh: '工程学博士', bg: 'Докторантура по инженерство', ur: 'انجینئرنگ میں پی ایچ ڈی', uz: 'Muhandislik fanlari doktori', sw: 'PhD katika Uhandisi', so: 'PhD-ka Injineeriyada', id: 'Doktor Teknik' },
    degreeLevel: 'phd',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-bus-phd',
    slug: 'business-phd',
    name: { en: 'PhD in Business', tr: 'İşletme Doktorası', az: 'Biznes Doktorantası', ru: 'Докторантура по бизнесу', de: 'Promotion im Wirtschaftsbereich', fr: 'Doctorat en commerce', fa: 'دکترای کسب و کار', ar: 'دكتوراه في إدارة الأعمال', tk: 'Biznes doktoranty', kk: 'Бизнес докторантурасы', ky: 'Бизнес докторантурасы', zh: '商学博士', bg: 'Докторантура по бизнес', ur: 'بزنس میں پی ایچ ڈی', uz: 'Biznes doktori', sw: 'PhD katika Biashara', so: 'PhD-ka Ganacsiga', id: 'Doktor Bisnis' },
    degreeLevel: 'phd',
    categorySlug: 'business',
    durationYears: 4,
  },
  {
    id: 'p-med-phd',
    slug: 'medicine-phd',
    name: { en: 'PhD in Medicine', tr: 'Tıp Doktorası', az: 'Tibb Doktorantası', ru: 'Докторантура по медицине', de: 'Promotion in Medizin', fr: 'Doctorat en médecine', fa: 'دکترای پزشکی', ar: 'دكتوراه في الطب', tk: 'Medisina doktoranty', kk: 'Медицина докторантурасы', ky: 'Медицина докторантурасы', zh: '医学博士', bg: 'Докторантура по медицина', ur: 'طب میں پی ایچ ڈی', uz: 'Tibbiyot doktori', sw: 'PhD katika Tiba', so: 'PhD-ka Caafimaadka', id: 'Doktor Kedokteran' },
    degreeLevel: 'phd',
    categorySlug: 'medicine',
    durationYears: 4,
  },
];
