import type { UniversityProgram } from "@/types";

/**
 * Links Azerbaijani universities to programs with tuition fees.
 * Tuition in USD/year for international students.
 * State universities are very affordable; private/ADA is higher.
 * Sources: ANAS, university official websites, Ministry of Education.
 */

export const seedUniversityPrograms: UniversityProgram[] = [
  // ═══════════════════════════════════════════════════════════════
  // BAKU STATE UNIVERSITY (BDU) — State, est. 1919
  // Largest & oldest university in Azerbaijan
  // ═══════════════════════════════════════════════════════════════
  {
    id: "up-bsu-med",
    universityId: "u-bsu",
    programId: "p-med-bach",
    language: "az",
    tuitionFee: 2000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-bsu-dent",
    universityId: "u-bsu",
    programId: "p-dent-bach",
    language: "az",
    tuitionFee: 2500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-bsu-cs",
    universityId: "u-bsu",
    programId: "p-cs-bach",
    language: "az",
    tuitionFee: 1200,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-bsu-cs-en",
    universityId: "u-bsu",
    programId: "p-cs-bach",
    language: "en",
    tuitionFee: 2500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-bsu-math",
    universityId: "u-bsu",
    programId: "p-eng-mech",
    language: "az",
    tuitionFee: 1000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-bsu-physics",
    universityId: "u-bsu",
    programId: "p-eng-elec",
    language: "az",
    tuitionFee: 1000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-bsu-chem",
    universityId: "u-bsu",
    programId: "p-eng-chemical",
    language: "az",
    tuitionFee: 1000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-bsu-biology",
    universityId: "u-bsu",
    programId: "p-eng-genetics",
    language: "az",
    tuitionFee: 1000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-bsu-law",
    universityId: "u-bsu",
    programId: "p-law-bach",
    language: "az",
    tuitionFee: 1200,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-bsu-bus",
    universityId: "u-bsu",
    programId: "p-bus-bach",
    language: "az",
    tuitionFee: 1200,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-bsu-econ",
    universityId: "u-bsu",
    programId: "p-bus-economics",
    language: "az",
    tuitionFee: 1200,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-bsu-arch",
    universityId: "u-bsu",
    programId: "p-arch-bach",
    language: "az",
    tuitionFee: 1500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-bsu-intl-rel",
    universityId: "u-bsu",
    programId: "p-bus-irm",
    language: "en",
    tuitionFee: 2500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-bsu-journalism",
    universityId: "u-bsu",
    programId: "p-arts-bach",
    language: "az",
    tuitionFee: 1000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-bsu-history",
    universityId: "u-bsu",
    programId: "p-hum-history",
    language: "az",
    tuitionFee: 1000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-bsu-literature",
    universityId: "u-bsu",
    programId: "p-hum-literature",
    language: "az",
    tuitionFee: 1000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-bsu-philosophy",
    universityId: "u-bsu",
    programId: "p-hum-philosophy",
    language: "az",
    tuitionFee: 1000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-bsu-sociology",
    universityId: "u-bsu",
    programId: "p-soc-sociology",
    language: "az",
    tuitionFee: 1000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-bsu-psychology",
    universityId: "u-bsu",
    programId: "p-health-psychology",
    language: "az",
    tuitionFee: 1200,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-bsu-pharmacy",
    universityId: "u-bsu",
    programId: "p-health-pharmacy",
    language: "az",
    tuitionFee: 2000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-bsu-nursing",
    universityId: "u-bsu",
    programId: "p-health-nursing",
    language: "az",
    tuitionFee: 1000,
    currency: "USD",
    scholarshipAvailable: true,
  },

  // ═══════════════════════════════════════════════════════════════
  // AZERBAIJAN DIPLOMATIC ACADEMY (ADA) — State, est. 2006
  // Premium international university in Baku
  // ═══════════════════════════════════════════════════════════════
  {
    id: "up-ada-ir",
    universityId: "u-ada",
    programId: "p-bus-irm",
    language: "en",
    tuitionFee: 12000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-ada-cs",
    universityId: "u-ada",
    programId: "p-cs-bach",
    language: "en",
    tuitionFee: 12000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-ada-ai",
    universityId: "u-ada",
    programId: "p-ai-master",
    language: "en",
    tuitionFee: 15000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-ada-cyber",
    universityId: "u-ada",
    programId: "p-cs-cybersecurity",
    language: "en",
    tuitionFee: 12000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-ada-data",
    universityId: "u-ada",
    programId: "p-cs-data-science",
    language: "en",
    tuitionFee: 12000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-ada-bus",
    universityId: "u-ada",
    programId: "p-bus-bach",
    language: "en",
    tuitionFee: 12000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-ada-pubadmin",
    universityId: "u-ada",
    programId: "p-soc-public-admin",
    language: "en",
    tuitionFee: 12000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-ada-translation",
    universityId: "u-ada",
    programId: "p-hum-translation",
    language: "en",
    tuitionFee: 10000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-ada-mba",
    universityId: "u-ada",
    programId: "p-bus-mba",
    language: "en",
    tuitionFee: 18000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-ada-energy",
    universityId: "u-ada",
    programId: "p-eng-energy",
    language: "en",
    tuitionFee: 12000,
    currency: "USD",
    scholarshipAvailable: true,
  },

  // ═══════════════════════════════════════════════════════════════
  // AZERBAIJAN UNIVERSITY OF ARCHITECTURE & CONSTRUCTION (ADNSU)
  // State, est. 1920 — Technical university
  // ═══════════════════════════════════════════════════════════════
  {
    id: "up-adnsu-arch",
    universityId: "u-odu",
    programId: "p-arch-bach",
    language: "az",
    tuitionFee: 1500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-adnsu-civil",
    universityId: "u-odu",
    programId: "p-eng-civil",
    language: "az",
    tuitionFee: 1500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-adnsu-civil-en",
    universityId: "u-odu",
    programId: "p-eng-civil",
    language: "en",
    tuitionFee: 3000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-adnsu-mech",
    universityId: "u-odu",
    programId: "p-eng-mech",
    language: "az",
    tuitionFee: 1500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-adnsu-elec",
    universityId: "u-odu",
    programId: "p-eng-elec",
    language: "az",
    tuitionFee: 1500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-adnsu-design",
    universityId: "u-odu",
    programId: "p-arts-bach",
    language: "az",
    tuitionFee: 1500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-adnsu-env",
    universityId: "u-odu",
    programId: "p-eng-environmental",
    language: "az",
    tuitionFee: 1500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-adnsu-infosys",
    universityId: "u-odu",
    programId: "p-cs-info-systems",
    language: "az",
    tuitionFee: 1500,
    currency: "USD",
    scholarshipAvailable: true,
  },

  // ═══════════════════════════════════════════════════════════════
  // NATIONAL AVIATION ACADEMY (MAA) — State, est. 1992
  // (u-aau legacy id merged into u-maa — same institution, aviation programs)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "up-aau-aero",
    universityId: "u-maa",
    programId: "p-eng-aerospace",
    language: "az",
    tuitionFee: 2000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-aau-aero-en",
    universityId: "u-maa",
    programId: "p-eng-aerospace",
    language: "en",
    tuitionFee: 4000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-aau-mech",
    universityId: "u-maa",
    programId: "p-eng-mech",
    language: "az",
    tuitionFee: 2000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-aau-elec",
    universityId: "u-maa",
    programId: "p-eng-elec",
    language: "az",
    tuitionFee: 2000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-aau-cs",
    universityId: "u-maa",
    programId: "p-cs-bach",
    language: "az",
    tuitionFee: 2000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-aau-energy",
    universityId: "u-maa",
    programId: "p-eng-energy",
    language: "az",
    tuitionFee: 2000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-aau-petroleum",
    universityId: "u-maa",
    programId: "p-eng-petroleum",
    language: "az",
    tuitionFee: 2000,
    currency: "USD",
    scholarshipAvailable: true,
  },

  // ═══════════════════════════════════════════════════════════════
  // SUMQAYIT STATE UNIVERSITY (SSU) — State, est. 2000
  // ═══════════════════════════════════════════════════════════════
  {
    id: "up-ssu-cs",
    universityId: "u-sdu",
    programId: "p-cs-bach",
    language: "az",
    tuitionFee: 1000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-ssu-mech",
    universityId: "u-sdu",
    programId: "p-eng-mech",
    language: "az",
    tuitionFee: 1000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-ssu-civil",
    universityId: "u-sdu",
    programId: "p-eng-civil",
    language: "az",
    tuitionFee: 1000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-ssu-elec",
    universityId: "u-sdu",
    programId: "p-eng-elec",
    language: "az",
    tuitionFee: 1000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-ssu-chem",
    universityId: "u-sdu",
    programId: "p-eng-chemical",
    language: "az",
    tuitionFee: 1000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-ssu-bus",
    universityId: "u-sdu",
    programId: "p-bus-bach",
    language: "az",
    tuitionFee: 1000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-ssu-econ",
    universityId: "u-sdu",
    programId: "p-bus-economics",
    language: "az",
    tuitionFee: 1000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-ssu-ecology",
    universityId: "u-sdu",
    programId: "p-eng-environmental",
    language: "az",
    tuitionFee: 1000,
    currency: "USD",
    scholarshipAvailable: true,
  },

  // ═══════════════════════════════════════════════════════════════
  // GANJA STATE UNIVERSITY (GSU) — State, est. 1939
  // ═══════════════════════════════════════════════════════════════
  {
    id: "up-gsu-philo",
    universityId: "u-gtu",
    programId: "p-hum-philosophy",
    language: "az",
    tuitionFee: 800,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-gsu-history",
    universityId: "u-gtu",
    programId: "p-hum-history",
    language: "az",
    tuitionFee: 800,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-gsu-literature",
    universityId: "u-gtu",
    programId: "p-hum-literature",
    language: "az",
    tuitionFee: 800,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-gsu-math",
    universityId: "u-gtu",
    programId: "p-cs-bach",
    language: "az",
    tuitionFee: 800,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-gsu-physics",
    universityId: "u-gtu",
    programId: "p-eng-elec",
    language: "az",
    tuitionFee: 800,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-gsu-chem",
    universityId: "u-gtu",
    programId: "p-eng-chemical",
    language: "az",
    tuitionFee: 800,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-gsu-biology",
    universityId: "u-gtu",
    programId: "p-eng-genetics",
    language: "az",
    tuitionFee: 800,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-gsu-law",
    universityId: "u-gtu",
    programId: "p-law-bach",
    language: "az",
    tuitionFee: 800,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-gsu-bus",
    universityId: "u-gtu",
    programId: "p-bus-bach",
    language: "az",
    tuitionFee: 800,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-gsu-econ",
    universityId: "u-gtu",
    programId: "p-bus-economics",
    language: "az",
    tuitionFee: 800,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-gsu-psychology",
    universityId: "u-gtu",
    programId: "p-health-psychology",
    language: "az",
    tuitionFee: 800,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-gsu-sociology",
    universityId: "u-gtu",
    programId: "p-soc-sociology",
    language: "az",
    tuitionFee: 800,
    currency: "USD",
    scholarshipAvailable: true,
  },

  // ═══════════════════════════════════════════════════════════════
  // GANJA STATE TECHNOLOGICAL UNIVERSITY (GSTU) — State, est. 1930
  // ═══════════════════════════════════════════════════════════════
  {
    id: "up-gstu-civil",
    universityId: "u-gtu-tech",
    programId: "p-eng-civil",
    language: "az",
    tuitionFee: 800,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-gstu-mech",
    universityId: "u-gtu-tech",
    programId: "p-eng-mech",
    language: "az",
    tuitionFee: 800,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-gstu-elec",
    universityId: "u-gtu-tech",
    programId: "p-eng-elec",
    language: "az",
    tuitionFee: 800,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-gstu-cs",
    universityId: "u-gtu-tech",
    programId: "p-cs-bach",
    language: "az",
    tuitionFee: 800,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-gstu-chem",
    universityId: "u-gtu-tech",
    programId: "p-eng-chemical",
    language: "az",
    tuitionFee: 800,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-gstu-food",
    universityId: "u-gtu-tech",
    programId: "p-eng-chemical",
    language: "az",
    tuitionFee: 800,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-gstu-energy",
    universityId: "u-gtu-tech",
    programId: "p-eng-energy",
    language: "az",
    tuitionFee: 800,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-gstu-auto",
    universityId: "u-gtu-tech",
    programId: "p-eng-automotive",
    language: "az",
    tuitionFee: 800,
    currency: "USD",
    scholarshipAvailable: true,
  },

  // ═══════════════════════════════════════════════════════════════
  // NAKHCHIVAN MEDICAL UNIVERSITY (NMU) — State, est. 2014
  // ═══════════════════════════════════════════════════════════════
  {
    id: "up-nmu-med",
    universityId: "u-nmu",
    programId: "p-med-bach",
    language: "az",
    tuitionFee: 3000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-nmu-med-en",
    universityId: "u-nmu",
    programId: "p-med-bach",
    language: "en",
    tuitionFee: 5000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-nmu-dent",
    universityId: "u-nmu",
    programId: "p-dent-bach",
    language: "az",
    tuitionFee: 3500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-nmu-dent-en",
    universityId: "u-nmu",
    programId: "p-dent-bach",
    language: "en",
    tuitionFee: 5500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-nmu-pharm",
    universityId: "u-nmu",
    programId: "p-health-pharmacy",
    language: "az",
    tuitionFee: 3000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-nmu-pharm-en",
    universityId: "u-nmu",
    programId: "p-health-pharmacy",
    language: "en",
    tuitionFee: 5000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-nmu-nursing",
    universityId: "u-nmu",
    programId: "p-health-nursing",
    language: "az",
    tuitionFee: 2500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-nmu-physio",
    universityId: "u-nmu",
    programId: "p-health-physio",
    language: "az",
    tuitionFee: 2500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  // Azerbaijan Medical University
  {
    id: "up-amu-med",
    universityId: "u-amu",
    programId: "p-med-bach",
    language: "en",
    tuitionFee: 5000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-amu-dent",
    universityId: "u-amu",
    programId: "p-dent-bach",
    language: "en",
    tuitionFee: 5000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-amu-pharm",
    universityId: "u-amu",
    programId: "p-health-pharmacy",
    language: "az",
    tuitionFee: 3000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  // UNEC
  {
    id: "up-unec-bus",
    universityId: "u-unec",
    programId: "p-bus-bach",
    language: "az",
    tuitionFee: 2000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-unec-bus-en",
    universityId: "u-unec",
    programId: "p-bus-bach",
    language: "en",
    tuitionFee: 3500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-unec-econ",
    universityId: "u-unec",
    programId: "p-bus-economics",
    language: "az",
    tuitionFee: 1800,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-unec-finance",
    universityId: "u-unec",
    programId: "p-bus-finance",
    language: "az",
    tuitionFee: 2000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  // Western University
  {
    id: "up-wu-bus",
    universityId: "u-wu",
    programId: "p-bus-bach",
    language: "en",
    tuitionFee: 4500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-wu-cs",
    universityId: "u-wu",
    programId: "p-cs-bach",
    language: "en",
    tuitionFee: 5000,
    currency: "USD",
    scholarshipAvailable: false,
  },
  {
    id: "up-wu-ir",
    universityId: "u-wu",
    programId: "p-bus-irm",
    language: "en",
    tuitionFee: 4000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  // Khazar University
  {
    id: "up-khazar-eng",
    universityId: "u-khazar",
    programId: "p-eng-mech",
    language: "en",
    tuitionFee: 5500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-khazar-cs",
    universityId: "u-khazar",
    programId: "p-cs-bach",
    language: "en",
    tuitionFee: 5500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-khazar-bus",
    universityId: "u-khazar",
    programId: "p-bus-bach",
    language: "en",
    tuitionFee: 5000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  // Baku Engineering University
  {
    id: "up-beu-cs",
    universityId: "u-beu",
    programId: "p-cs-bach",
    language: "en",
    tuitionFee: 4000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-beu-civil",
    universityId: "u-beu",
    programId: "p-eng-civil",
    language: "en",
    tuitionFee: 4000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-beu-info",
    universityId: "u-beu",
    programId: "p-cs-info-systems",
    language: "en",
    tuitionFee: 3800,
    currency: "USD",
    scholarshipAvailable: false,
  },
  // ASPU
  {
    id: "up-aspu-edu",
    universityId: "u-aspu",
    programId: "p-soc-political",
    language: "az",
    tuitionFee: 1200,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-aspu-history",
    universityId: "u-aspu",
    programId: "p-hum-history",
    language: "az",
    tuitionFee: 1200,
    currency: "USD",
    scholarshipAvailable: true,
  },
  // Lankaran State University
  {
    id: "up-lsu-bus",
    universityId: "u-lsu",
    programId: "p-bus-bach",
    language: "az",
    tuitionFee: 1000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-lsu-history",
    universityId: "u-lsu",
    programId: "p-hum-history",
    language: "az",
    tuitionFee: 1000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  // Mingachevir State University
  {
    id: "up-mgu-eng",
    universityId: "u-mgu",
    programId: "p-eng-mech",
    language: "az",
    tuitionFee: 1000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-mgu-econ",
    universityId: "u-mgu",
    programId: "p-bus-economics",
    language: "az",
    tuitionFee: 1000,
    currency: "USD",
    scholarshipAvailable: true,
  },
];
